apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: build-history-service
        component: backend
    name: build-history-service
    namespace: build-pipeline
spec:
    clusterIP: 10.106.34.152
    clusterIPs:
        - 10.106.34.152
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
    selector:
        app: build-history-service
    sessionAffinity: None
    type: ClusterIP
