apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: build-management-service
    name: build-management-service
    namespace: build-pipeline
spec:
    clusterIP: 10.98.231.253
    clusterIPs:
        - 10.98.231.253
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: websocket
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: build-management-service
    sessionAffinity: None
    type: ClusterIP
