apiVersion: v1
kind: Service
metadata:
    annotations:
        resource-spec-hash: "1797157087"
    labels:
        controller: eventbus-controller
        eventbus-name: default
        owner-name: default
        stan: "yes"
    name: eventbus-default-stan-svc
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: EventBus
          name: default
          uid: 00c4fad2-b7a9-4641-87fe-1762448e8fce
spec:
    clusterIPs:
        - None
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: tcp-client
          port: 4222
          protocol: TCP
          targetPort: 4222
        - name: cluster
          port: 6222
          protocol: TCP
          targetPort: 6222
        - name: monitor
          port: 8222
          protocol: TCP
          targetPort: 8222
    selector:
        controller: eventbus-controller
        eventbus-name: default
        owner-name: default
    sessionAffinity: None
    type: ClusterIP
