apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: frontend-service
    name: frontend-service
    namespace: build-pipeline
spec:
    clusterIP: 10.109.149.95
    clusterIPs:
        - 10.109.149.95
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: http
          nodePort: 32648
          port: 80
          protocol: TCP
          targetPort: 3000
    selector:
        app: frontend-service
    sessionAffinity: None
    type: NodePort
