apiVersion: v1
data:
    .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMDMuOTQuNzAiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoia2FpemVuIiwiZW1haWwiOiJhZG1pbkBoYXJib3IubG9jYWwiLCJhdXRoIjoiWVdSdGFXNDZhMkZwZW1WdSJ9fX0=
kind: Secret
metadata:
    name: harbor-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
