apiVersion: v1
data:
    git-branch: bWFpbg==
    git-email: YmVya2F5c2lzbGlAZ21haWwuY29t
    git-repository: aHR0cHM6Ly9naXRodWIuY29tL3dhbGJpcy9iYWNrdXB0ZXN0LmdpdA==
    git-token: Z2hwX0VtYW0wRENNQ1gxMnljT2RZOHNVeGhMMHRRakxSSDE5aHg0UQ==
    git-username: d2FsYmlz
    minio-access-key: YWRtaW4=
    minio-bucket: Y2x1c3Rlci1iYWNrdXBz
    minio-endpoint: aG9zdC5taW5pa3ViZS5pbnRlcm5hbDo5MDAw
    minio-secret-key: YWRtaW4xMjM0NTY=
    minio-use-ssl: ZmFsc2U=
    retry-attempts: Mw==
    retry-delay: NXM=
    ssh-private-key: ""
    work-dir: L3dvcmtzcGFjZQ==
kind: Secret
metadata:
    annotations: {}
    labels:
        app: git-sync
        component: secrets
    name: git-sync-secrets
    namespace: test-backup
type: Opaque
