apiVersion: apps/v1
kind: ReplicaSet
metadata:
    annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        resource-spec-hash: "998662875"
    labels:
        controller: eventsource-controller
        eventsource-name: buildkit-webhook
        owner-name: buildkit-webhook
        pod-template-hash: 687bfbdc44
    name: buildkit-webhook-eventsource-5vb4f-687bfbdc44
    namespace: argo-events
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: buildkit-webhook-eventsource-5vb4f
          uid: ad314571-24ba-4a37-bbd3-da862f129252
spec:
    replicas: 1
    selector:
        matchLabels:
            controller: eventsource-controller
            eventsource-name: buildkit-webhook
            owner-name: buildkit-webhook
            pod-template-hash: 687bfbdc44
    template:
        metadata:
            creationTimestamp: null
            labels:
                controller: eventsource-controller
                eventsource-name: buildkit-webhook
                owner-name: buildkit-webhook
                pod-template-hash: 687bfbdc44
        spec:
            containers:
                - args:
                    - eventsource-service
                  env:
                    - name: EVENTSOURCE_OBJECT
                      value: eyJtZXRhZGF0YSI6eyJuYW1lIjoiYnVpbGRraXQtd2ViaG9vayIsIm5hbWVzcGFjZSI6ImFyZ28tZXZlbnRzIiwiY3JlYXRpb25UaW1lc3RhbXAiOm51bGx9LCJzcGVjIjp7IndlYmhvb2siOnsiYnVpbGRraXQtdHJpZ2dlciI6eyJlbmRwb2ludCI6Ii9idWlsZGtpdCIsIm1ldGhvZCI6IlBPU1QiLCJwb3J0IjoiMTIwMDAiLCJ1cmwiOiIifX19LCJzdGF0dXMiOnt9fQ==
                    - name: EVENTBUS_SUBJECT
                      value: eventbus-argo-events
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                    - name: LEADER_ELECTION
                    - name: EVENTBUS_CONFIG
                      value: eyJuYXRzIjp7InVybCI6Im5hdHM6Ly9ldmVudGJ1cy1kZWZhdWx0LXN0YW4tc3ZjOjQyMjIiLCJjbHVzdGVySUQiOiJldmVudGJ1cy1kZWZhdWx0IiwiYXV0aCI6InRva2VuIiwiYWNjZXNzU2VjcmV0Ijp7Im5hbWUiOiJldmVudGJ1cy1kZWZhdWx0LWNsaWVudCIsImtleSI6ImNsaWVudC1hdXRoIn19fQ==
                  image: quay.io/argoproj/argo-events:v1.9.6
                  imagePullPolicy: Always
                  name: main
                  ports:
                    - containerPort: 7777
                      name: metrics
                      protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /etc/eventbus/auth
                      name: auth-volume
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: auth-volume
                  secret:
                    defaultMode: 420
                    items:
                        - key: client-auth
                          path: auth.yaml
                    secretName: eventbus-default-client
                - emptyDir: {}
                  name: tmp
