{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
---
# Backup ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-backup-metrics
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.backupLabels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    description: "Prometheus monitoring for OpenShift cluster backup service"
spec:
  selector:
    matchLabels:
      {{- include "cluster-backup-openshift.backupSelectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ include "cluster-backup-openshift.namespace" . }}
{{- if and .Values.gitSync.enabled .Values.git.enabled }}
---
# Git-Sync ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-git-sync-metrics
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.gitSyncLabels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    description: "Prometheus monitoring for OpenShift cluster git-sync service"
spec:
  selector:
    matchLabels:
      {{- include "cluster-backup-openshift.gitSyncSelectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ include "cluster-backup-openshift.namespace" . }}
{{- end }}
{{- end }}

{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled }}
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-alerts
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    prometheus: kube-prometheus
    role: alert-rules
  annotations:
    description: "Alerting rules for OpenShift cluster backup service"
spec:
  groups:
  - name: {{ include "cluster-backup-openshift.fullname" . }}.rules
    rules:
    {{- if .Values.monitoring.prometheusRule.rules.backupFailure }}
    - alert: OpenShiftBackupJobFailed
      expr: increase(cluster_backup_errors_total{cluster="{{ .Values.cluster.name }}"}[1h]) > 0
      for: 5m
      labels:
        severity: critical
        service: cluster-backup
        platform: openshift
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "OpenShift Backup Job Failed"
        description: "Backup job has failed {{ "{{ $value }}" }} times in the last hour for cluster {{ .Values.cluster.name }}"
    {{- end }}
    
    {{- if .Values.monitoring.prometheusRule.rules.backupNotRunning }}
    - alert: OpenShiftBackupJobNotRunning
      expr: time() - cluster_backup_last_success_timestamp{cluster="{{ .Values.cluster.name }}"} > 86400
      for: 5m
      labels:
        severity: warning
        service: cluster-backup
        platform: openshift
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "OpenShift Backup Job Not Running"
        description: "No successful backup in the last 24 hours for cluster {{ .Values.cluster.name }}"
    {{- end }}
    
    {{- if .Values.monitoring.prometheusRule.rules.highBackupDuration }}
    - alert: OpenShiftBackupHighDuration
      expr: cluster_backup_duration_seconds{cluster="{{ .Values.cluster.name }}"} > 3600
      for: 2m
      labels:
        severity: warning
        service: cluster-backup
        platform: openshift
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "OpenShift Backup Taking Too Long"
        description: "Backup for cluster {{ .Values.cluster.name }} took {{ "{{ $value }}" }} seconds to complete"
    {{- end }}
    
    {{- if and .Values.monitoring.prometheusRule.rules.gitSyncFailure .Values.gitSync.enabled }}
    - alert: OpenShiftGitSyncFailed
      expr: increase(git_sync_errors_total{cluster="{{ .Values.cluster.name }}"}[1h]) > 0
      for: 5m
      labels:
        severity: warning
        service: git-sync
        platform: openshift
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "OpenShift Git Sync Failed"
        description: "Git sync failed {{ "{{ $value }}" }} times in the last hour for cluster {{ .Values.cluster.name }}"
    {{- end }}
{{- end }}