{{- if .Values.rbac.create }}
---
# ClusterRole for backup operations  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-reader
  labels:
    {{- include "cluster-backup-openshift.backupLabels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# All API groups and resources - read only access
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for backup ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-binding
  labels:
    {{- include "cluster-backup-openshift.backupLabels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-backup-openshift.serviceAccountName" . }}
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "cluster-backup-openshift.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}