apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-backup-openshift.secretName" . }}
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.backupLabels" . | nindent 4 }}
  annotations:
    description: "Configuration secrets for OpenShift cluster backup service"
type: Opaque
stringData:
  # Cluster Configuration
  cluster-domain: {{ .Values.cluster.domain | quote }}
  cluster-name: {{ .Values.cluster.name | quote }}
  
  # MinIO Configuration
  minio-endpoint: {{ .Values.minio.endpoint | quote }}
  minio-bucket: {{ .Values.minio.bucket | quote }}
  minio-use-ssl: {{ .Values.minio.useSSL | quote }}
  minio-access-key: {{ .Values.minio.credentials.accessKey | quote }}
  minio-secret-key: {{ .Values.minio.credentials.secretKey | quote }}
  
  # Backup Configuration
  {{- if .Values.backup.filtering.excludeNamespaces }}
  exclude-namespaces: |
    {{- range .Values.backup.filtering.excludeNamespaces }}
    {{ . }}
    {{- end }}
    {{- range .Values.backup.config.additionalExcludeNamespaces }}
    {{ . }}
    {{- end }}
  {{- end }}
  batch-size: {{ .Values.backup.config.batchSize | quote }}
  retry-attempts: {{ .Values.backup.config.retryAttempts | quote }}
  retry-delay: {{ .Values.backup.config.retryDelay | quote }}
  log-level: {{ .Values.backup.config.logLevel | quote }}
  
  # Cleanup Configuration
  enable-cleanup: {{ .Values.backup.config.enableCleanup | quote }}
  retention-days: {{ .Values.backup.config.retentionDays | quote }}
  cleanup-on-startup: {{ .Values.backup.config.cleanupOnStartup | quote }}
  
  {{- if .Values.git.enabled }}
  # Git Configuration (if enabled)
  git-repository: {{ .Values.git.repository | quote }}
  git-branch: {{ .Values.git.branch | quote }}
  git-username: {{ .Values.git.user.name | quote }}
  git-email: {{ .Values.git.user.email | quote }}
  {{- if .Values.git.auth.token }}
  git-token: {{ .Values.git.auth.token | quote }}
  {{- end }}
  {{- if .Values.git.auth.sshPrivateKey }}
  git-ssh-private-key: {{ .Values.git.auth.sshPrivateKey | quote }}
  {{- end }}
  {{- end }}