{{- if .Values.monitoring.enabled }}
---
# Backup Metrics Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-backup-metrics
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.backupLabels" . | nindent 4 }}
  {{- with .Values.monitoring.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.monitoring.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.monitoring.service.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "cluster-backup-openshift.backupSelectorLabels" . | nindent 4 }}
{{- if and .Values.gitSync.enabled .Values.git.enabled }}
---
# Git-Sync Metrics Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-backup-openshift.fullname" . }}-git-sync-metrics
  namespace: {{ include "cluster-backup-openshift.namespace" . }}
  labels:
    {{- include "cluster-backup-openshift.gitSyncLabels" . | nindent 4 }}
  {{- with .Values.monitoring.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.monitoring.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.monitoring.service.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "cluster-backup-openshift.gitSyncSelectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}