---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-backup
  namespace: openshift-backup
  labels:
    app: cluster-backup
    component: backup-cronjob
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 7200  # 2 hours timeout
      template:
        metadata:
          labels:
            app: cluster-backup
            component: backup-job
        spec:
          serviceAccountName: cluster-backup
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: backup
            image: registry.redhat.io/ubi9/ubi:latest
            imagePullPolicy: Always
            command:
            - /usr/local/bin/cluster-backup
            env:
            - name: CLUSTER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: cluster-domain
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: cluster-name
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: minio-endpoint
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: minio-bucket
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: minio-use-ssl
            - name: EXCLUDE_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: exclude-namespaces
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-secret-key
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /.cache
            ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          volumes:
          - name: tmp
            emptyDir: {}
          - name: cache
            emptyDir: {}
          tolerations:
          - operator: Exists
            effect: NoSchedule
          - operator: Exists
            effect: NoExecute
          nodeSelector:
            kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-backup-metrics
  namespace: openshift-backup
  labels:
    app: cluster-backup
    component: metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cluster-backup
    component: backup-job
  type: ClusterIP