---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-multicluster-minio
  namespace: test-backup
spec:
  template:
    spec:
      serviceAccountName: cluster-backup
      restartPolicy: Never
      containers:
      - name: minio-check
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          # Configure MinIO client
          mc alias set myminio http://host.minikube.internal:9000 admin admin123456
          
          echo "=== Checking new multi-cluster path structure ==="
          echo "Expected path: clusterbackup/test-multicluster/"
          echo ""
          
          echo "=== Root bucket structure ==="
          mc ls myminio/cluster-backups/ || echo "No files found"
          echo ""
          
          echo "=== New clusterbackup folder ==="
          mc ls myminio/cluster-backups/clusterbackup/ || echo "No clusterbackup folder found"
          echo ""
          
          echo "=== Test cluster folder ==="
          mc ls myminio/cluster-backups/clusterbackup/test-multicluster/ || echo "No test-multicluster folder found"
          echo ""
          
          echo "=== Sample files in test-multicluster ==="
          mc ls --recursive myminio/cluster-backups/clusterbackup/test-multicluster/ | head -10 || echo "No files found"
          echo ""
          
          echo "=== Counting total files ==="
          mc ls --recursive myminio/cluster-backups/clusterbackup/test-multicluster/ | wc -l || echo "Count failed"
      restartPolicy: Never