---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-git-sync-incremental
  namespace: test-backup
  labels:
    app: git-sync
    component: incremental-test
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: git-sync
        component: incremental-test
    spec:
      serviceAccountName: cluster-backup
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: git-sync
        image: git-sync:multicluster-test-working
        imagePullPolicy: Never
        env:
        # MinIO Configuration (read from new path structure)
        - name: MINIO_ENDPOINT
          value: "host.minikube.internal:9000"
        - name: MINIO_BUCKET
          value: "cluster-backups"
        - name: MINIO_USE_SSL
          value: "false"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "admin123456"
        
        # Git Configuration (test repository)
        - name: GIT_REPOSITORY
          value: ""  # Empty to test download-only mode
        - name: GIT_BRANCH
          value: "main"
        - name: GIT_USERNAME
          value: "automated-backup"
        - name: GIT_EMAIL
          value: "backup@test.local"
        - name: GIT_TOKEN
          value: ""  # Empty for testing - would fail on push but that's ok for this test
        
        # Working directory
        - name: WORK_DIR
          value: "/workspace"
        - name: RETRY_ATTEMPTS
          value: "2"
        - name: RETRY_DELAY
          value: "5s"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: tmp
        emptyDir: {}
      - name: workspace
        emptyDir: {}