apiVersion: batch/v1
kind: Job
metadata:
    annotations: {}
    labels:
        batch.kubernetes.io/controller-uid: f44c1c03-d7d0-4070-b1ac-cbe1d5df7cfb
        batch.kubernetes.io/job-name: minio-connection-test
        controller-uid: f44c1c03-d7d0-4070-b1ac-cbe1d5df7cfb
        job-name: minio-connection-test
    name: minio-connection-test
    namespace: build-pipeline
spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
        matchLabels:
            batch.kubernetes.io/controller-uid: f44c1c03-d7d0-4070-b1ac-cbe1d5df7cfb
    suspend: false
    template:
        metadata:
            creationTimestamp: null
            labels:
                batch.kubernetes.io/controller-uid: f44c1c03-d7d0-4070-b1ac-cbe1d5df7cfb
                batch.kubernetes.io/job-name: minio-connection-test
                controller-uid: f44c1c03-d7d0-4070-b1ac-cbe1d5df7cfb
                job-name: minio-connection-test
        spec:
            containers:
                - args:
                    - |
                      echo "=== MinIO Connection Test ==="

                      # Configure MinIO client
                      mc alias set minio http://host.docker.internal:9000 admin kaizen123

                      # Test connection
                      mc admin info minio

                      # Create bucket if not exists
                      mc mb minio/build-logs --ignore-existing

                      # Create test file
                      echo "Test log content $(date)" > /tmp/test.log

                      # Upload test file
                      mc cp /tmp/test.log minio/build-logs/test.log

                      # List bucket contents
                      mc ls minio/build-logs/

                      echo "=== MinIO Connection Test Completed ==="
                  command:
                    - sh
                    - -c
                  env:
                    - name: MC_HOST_minio
                      value: http://admin:kaizen123@host.docker.internal:9000
                  image: minio/mc:latest
                  imagePullPolicy: Always
                  name: minio-test
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
