{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cluster-backup.fullname" . }}-backup
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  timeZone: "UTC"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            {{- include "cluster-backup.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: backup
        spec:
          serviceAccountName: {{ include "cluster-backup.serviceAccountName" . }}
          restartPolicy: Never
          {{- with (include "cluster-backup.podSecurityContext" . | fromYaml) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: backup
            image: {{ include "cluster-backup.backupImage" . }}
            imagePullPolicy: {{ include "cluster-backup.pullPolicy" . }}
            env:
            # Cluster identification
            - name: CLUSTER_NAME
              value: {{ .Values.cluster.name | quote }}
            - name: CLUSTER_DOMAIN
              value: {{ .Values.cluster.domain | quote }}
            
            # MinIO Configuration
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
                  key: minio-endpoint
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
                  key: minio-bucket
            - name: MINIO_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
                  key: minio-use-ssl
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
                  key: minio-secret-key
            
            # Configuration
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.backup.config.logLevel | quote }}
            
            {{- with .Values.extra.backupEnvVars }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            
            resources:
              {{- toYaml .Values.backup.resources | nindent 14 }}
            
            {{- with (include "cluster-backup.securityContext" . | fromYaml) }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: workspace
              mountPath: /workspace
            {{- if .Values.persistence.enabled }}
            - name: backup-storage
              mountPath: /data
            {{- end }}
            
            ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
              
          volumes:
          - name: tmp
            emptyDir: {}
          - name: workspace
            emptyDir: {}
          {{- if .Values.persistence.enabled }}
          - name: backup-storage
            persistentVolumeClaim:
              claimName: {{ include "cluster-backup.fullname" . }}-backup-pvc
          {{- end }}
          
          {{- with .Values.backup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.backup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.backup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}