{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
---
# Backup ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cluster-backup.fullname" . }}-backup-metrics
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cluster-backup.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backup
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics

{{- if .Values.gitSync.enabled }}
---
# Git-Sync ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cluster-backup.fullname" . }}-git-sync-metrics
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: git-sync
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cluster-backup.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: git-sync
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
{{- end }}

{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled }}
---
# Prometheus Alerting Rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cluster-backup.fullname" . }}-alerts
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "cluster-backup.fullname" . }}.rules
    rules:
    {{- if .Values.monitoring.prometheusRule.rules.backupFailure }}
    - alert: BackupJobFailed
      expr: increase(cluster_backup_errors_total{cluster="{{ .Values.cluster.name }}"}[1h]) > 0
      for: 5m
      labels:
        severity: critical
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "Kubernetes Backup Job Failed"
        description: "Backup job has failed {{ "{{ $value }}" }} times in the last hour for cluster {{ .Values.cluster.name }}"
    {{- end }}
    
    {{- if .Values.monitoring.prometheusRule.rules.backupNotRunning }}
    - alert: BackupJobNotRunning
      expr: time() - cluster_backup_last_success_timestamp{cluster="{{ .Values.cluster.name }}"} > 86400
      for: 5m
      labels:
        severity: warning
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "Backup Job Not Running"
        description: "No successful backup in the last 24 hours for cluster {{ .Values.cluster.name }}"
    {{- end }}
    
    {{- if and .Values.gitSync.enabled .Values.monitoring.prometheusRule.rules.gitSyncFailure }}
    - alert: GitSyncFailed
      expr: increase(git_sync_errors_total[1h]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Git Sync Failed"
        description: "Git sync has failed {{ "{{ $value }}" }} times in the last hour"
    {{- end }}
    
    {{- if .Values.monitoring.prometheusRule.rules.highBackupDuration }}
    - alert: HighBackupDuration
      expr: cluster_backup_duration_seconds{cluster="{{ .Values.cluster.name }}"} > 3600
      for: 2m
      labels:
        severity: warning
        cluster: {{ .Values.cluster.name }}
      annotations:
        summary: "Backup Taking Too Long"
        description: "Backup for cluster {{ .Values.cluster.name }} took {{ "{{ $value }}" }} seconds to complete"
    {{- end }}
{{- end }}