---
# Backup Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-backup.fullname" . }}-backup-secrets
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
type: Opaque
data:
  # MinIO Configuration
  minio-endpoint: {{ .Values.minio.endpoint | b64enc | quote }}
  minio-bucket: {{ .Values.minio.bucket | b64enc | quote }}
  minio-use-ssl: {{ .Values.minio.useSSL | toString | b64enc | quote }}
  minio-access-key: {{ .Values.minio.credentials.accessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.minio.credentials.secretKey | b64enc | quote }}
  
  # Cluster Configuration
  cluster-name: {{ .Values.cluster.name | b64enc | quote }}
  cluster-domain: {{ .Values.cluster.domain | b64enc | quote }}

{{- if .Values.gitSync.enabled }}
---
# Git-Sync Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-backup.fullname" . }}-git-sync-secrets
  namespace: {{ include "cluster-backup.namespace" . }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: git-sync
  annotations:
    {{- include "cluster-backup.annotations" . | nindent 4 }}
type: Opaque
data:
  # MinIO Configuration (same as backup)
  minio-endpoint: {{ .Values.minio.endpoint | b64enc | quote }}
  minio-bucket: {{ .Values.minio.bucket | b64enc | quote }}
  minio-use-ssl: {{ .Values.minio.useSSL | toString | b64enc | quote }}
  minio-access-key: {{ .Values.minio.credentials.accessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.minio.credentials.secretKey | b64enc | quote }}
  
  # Git Configuration
  git-repository: {{ .Values.git.repository | b64enc | quote }}
  git-branch: {{ .Values.git.branch | b64enc | quote }}
  git-username: {{ .Values.git.user.name | b64enc | quote }}
  git-email: {{ .Values.git.user.email | b64enc | quote }}
  
  {{- if .Values.git.auth.token }}
  git-token: {{ .Values.git.auth.token | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.git.auth.sshPrivateKey }}
  ssh-private-key: {{ .Values.git.auth.sshPrivateKey | b64enc | quote }}
  {{- end }}
  
  # Additional Configuration
  work-dir: {{ .Values.gitSync.workDir | b64enc | quote }}
  retry-attempts: {{ .Values.gitSync.config.retryAttempts | toString | b64enc | quote }}
  retry-delay: {{ .Values.gitSync.config.retryDelay | b64enc | quote }}
{{- end }}