apiVersion: v1
data:
    _REDIS_URL_CORE: redis://harbor-redis:6379/0?idle_timeout_seconds=30
    _REDIS_URL_REG: redis://harbor-redis:6379/2?idle_timeout_seconds=30
    CHART_CACHE_DRIVER: redis
    CONFIG_PATH: /etc/core/app.conf
    CORE_LOCAL_URL: http://127.0.0.1:8080
    CORE_URL: http://harbor-core:80
    DATABASE_TYPE: postgresql
    EXT_ENDPOINT: http://10.103.94.70
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    JOBSERVICE_URL: http://harbor-jobservice
    LOG_LEVEL: info
    NO_PROXY: harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal
    PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry,github-ghcr,jfrog-artifactory
    PORT: "8080"
    PORTAL_URL: http://harbor-portal
    POSTGRESQL_DATABASE: registry
    POSTGRESQL_HOST: harbor-database
    POSTGRESQL_MAX_IDLE_CONNS: "100"
    POSTGRESQL_MAX_OPEN_CONNS: "900"
    POSTGRESQL_PORT: "5432"
    POSTGRESQL_SSLMODE: disable
    POSTGRESQL_USERNAME: postgres
    QUOTA_UPDATE_PROVIDER: db
    REGISTRY_CONTROLLER_URL: http://harbor-registry:8080
    REGISTRY_CREDENTIAL_USERNAME: harbor_registry_user
    REGISTRY_STORAGE_PROVIDER_NAME: filesystem
    REGISTRY_URL: http://harbor-registry:5000
    TOKEN_SERVICE_URL: http://harbor-core:80/service/token
    TRIVY_ADAPTER_URL: http://harbor-trivy:8080
    WITH_TRIVY: "false"
    app.conf: |
        appname = Harbor
        runmode = prod
        enablegzip = true

        [prod]
        httpport = 8080
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: harbor
        meta.helm.sh/release-namespace: harbor
    labels:
        app: harbor
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: harbor
        app.kubernetes.io/part-of: harbor
        app.kubernetes.io/version: 2.13.1
        chart: harbor
        heritage: Helm
        release: harbor
    name: harbor-core
    namespace: harbor
