apiVersion: v1
data:
    CORE_URL: http://harbor-core:80
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    JOBSERVICE_WEBHOOK_JOB_HTTP_CLIENT_TIMEOUT: "3"
    JOBSERVICE_WEBHOOK_JOB_MAX_RETRY: "3"
    LOG_LEVEL: info
    NO_PROXY: harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal
    REGISTRY_CONTROLLER_URL: http://harbor-registry:8080
    REGISTRY_CREDENTIAL_USERNAME: harbor_registry_user
    REGISTRY_URL: http://harbor-registry:5000
    TOKEN_SERVICE_URL: http://harbor-core:80/service/token
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: harbor
        meta.helm.sh/release-namespace: harbor
    labels:
        app: harbor
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: harbor
        app.kubernetes.io/part-of: harbor
        app.kubernetes.io/version: 2.13.1
        chart: harbor
        heritage: Helm
        release: harbor
    name: harbor-jobservice-env
    namespace: harbor
