apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    annotations: {}
    name: workflow-role
    namespace: build-pipeline
rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - pods/log
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - apiGroups:
        - ""
      resources:
        - secrets
        - configmaps
      verbs:
        - get
        - list
    - apiGroups:
        - argoproj.io
      resources:
        - workflows
        - workflowtemplates
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
