apiVersion: v1
kind: Service
metadata:
    annotations: {}
    name: argo-server
    namespace: argo
spec:
    clusterIP: 10.106.182.31
    clusterIPs:
        - 10.106.182.31
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: web
          port: 2746
          protocol: TCP
          targetPort: 2746
    selector:
        app: argo-server
    sessionAffinity: None
    type: ClusterIP
