apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
        pv.kubernetes.io/bind-completed: "yes"
        pv.kubernetes.io/bound-by-controller: "yes"
        volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
        volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    finalizers:
        - kubernetes.io/pvc-protection
    name: build-workspace-pvc
    namespace: build-pipeline
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-89587721-7f7a-4a53-bd69-17f27c00ce71
