apiVersion: v1
kind: Pod
metadata:
    generateName: workflow-controller-794db774c9-
    labels:
        app: workflow-controller
        pod-template-hash: 794db774c9
    name: workflow-controller-794db774c9-frlcd
    namespace: argo
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: workflow-controller-794db774c9
          uid: 5ae68032-e310-47f2-bec8-5c0ae10797d9
spec:
    containers:
        - command:
            - workflow-controller
          env:
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
          image: quay.io/argoproj/workflow-controller:v3.5.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /healthz
                port: 6060
                scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          name: workflow-controller
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-5tsr5
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeSelector:
        kubernetes.io/os: linux
    preemptionPolicy: PreemptLowerPriority
    priority: 1000000
    priorityClassName: workflow-controller
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
        runAsNonRoot: true
    serviceAccount: argo
    serviceAccountName: argo
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: kube-api-access-5tsr5
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
