apiVersion: apps/v1
kind: Deployment
metadata:
    annotations: {}
    name: argo-server
    namespace: argo
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: argo-server
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: argo-server
        spec:
            containers:
                - args:
                    - server
                  image: quay.io/argoproj/argocli:v3.5.5
                  imagePullPolicy: IfNotPresent
                  name: argo-server
                  ports:
                    - containerPort: 2746
                      name: web
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /
                        port: 2746
                        scheme: HTTPS
                    initialDelaySeconds: 10
                    periodSeconds: 20
                    successThreshold: 1
                    timeoutSeconds: 1
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            nodeSelector:
                kubernetes.io/os: linux
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
            serviceAccount: argo-server
            serviceAccountName: argo-server
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: tmp
