apiVersion: apps/v1
kind: Deployment
metadata:
    annotations: {}
    name: workflow-controller
    namespace: argo
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: workflow-controller
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: workflow-controller
        spec:
            containers:
                - command:
                    - workflow-controller
                  env:
                    - name: LEADER_ELECTION_IDENTITY
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                  image: quay.io/argoproj/workflow-controller:v3.5.5
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /healthz
                        port: 6060
                        scheme: HTTP
                    initialDelaySeconds: 90
                    periodSeconds: 60
                    successThreshold: 1
                    timeoutSeconds: 30
                  name: workflow-controller
                  ports:
                    - containerPort: 9090
                      name: metrics
                      protocol: TCP
                    - containerPort: 6060
                      protocol: TCP
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            nodeSelector:
                kubernetes.io/os: linux
            priorityClassName: workflow-controller
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
            serviceAccount: argo
            serviceAccountName: argo
            terminationGracePeriodSeconds: 30
