apiVersion: v1
kind: Pod
metadata:
    annotations: {}
    labels:
        app: cluster-backup
        component: test
    name: backup-test
    namespace: test-backup
spec:
    containers:
        - args:
            - -c
            - while true; do sleep 30; done
          command:
            - /bin/sh
          env:
            - name: CLUSTER_DOMAIN
              valueFrom:
                configMapKeyRef:
                    key: cluster-domain
                    name: backup-config
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                    key: cluster-name
                    name: backup-config
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                    key: minio-endpoint
                    name: backup-config
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                    key: minio-bucket
                    name: backup-config
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                    key: minio-use-ssl
                    name: backup-config
            - name: EXCLUDE_NAMESPACES
              valueFrom:
                configMapKeyRef:
                    key: exclude-namespaces
                    name: backup-config
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-access-key
                    name: backup-secrets
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-secret-key
                    name: backup-secrets
            - name: LOG_LEVEL
              value: debug
          image: golang:1.21-alpine
          imagePullPolicy: IfNotPresent
          name: backup
          resources:
            limits:
                cpu: 500m
                memory: 512Mi
            requests:
                cpu: 100m
                memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /workspace
              name: workdir
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-2g57x
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
    serviceAccount: cluster-backup
    serviceAccountName: cluster-backup
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: workdir
        - name: kube-api-access-2g57x
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
