apiVersion: v1
kind: Pod
metadata:
    generateName: backup-cronjob-test-29205614-
    labels:
        app: cluster-backup
        batch.kubernetes.io/controller-uid: 1ecb8db1-fd81-44d4-b0fc-dec5bf8d1d9d
        batch.kubernetes.io/job-name: backup-cronjob-test-29205614
        component: test-job
        controller-uid: 1ecb8db1-fd81-44d4-b0fc-dec5bf8d1d9d
        job-name: backup-cronjob-test-29205614
    name: backup-cronjob-test-29205614-xrw2x
    namespace: test-backup
    ownerReferences:
        - apiVersion: batch/v1
          blockOwnerDeletion: true
          controller: true
          kind: Job
          name: backup-cronjob-test-29205614
          uid: 1ecb8db1-fd81-44d4-b0fc-dec5bf8d1d9d
spec:
    containers:
        - env:
            - name: CLUSTER_DOMAIN
              valueFrom:
                configMapKeyRef:
                    key: cluster-domain
                    name: backup-config
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                    key: cluster-name
                    name: backup-config
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                    key: minio-endpoint
                    name: backup-config
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                    key: minio-bucket
                    name: backup-config
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                    key: minio-use-ssl
                    name: backup-config
            - name: EXCLUDE_NAMESPACES
              valueFrom:
                configMapKeyRef:
                    key: exclude-namespaces
                    name: backup-config
            - name: BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                    key: batch-size
                    name: backup-config
            - name: RETRY_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                    key: retry-attempts
                    name: backup-config
            - name: RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                    key: retry-delay
                    name: backup-config
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                    key: log-level
                    name: backup-config
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-access-key
                    name: backup-secrets
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-secret-key
                    name: backup-secrets
          image: cluster-backup:test
          imagePullPolicy: Never
          name: backup
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            limits:
                cpu: 500m
                memory: 512Mi
            requests:
                cpu: 100m
                memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-fzss8
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: OnFailure
    schedulerName: default-scheduler
    securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
    serviceAccount: cluster-backup
    serviceAccountName: cluster-backup
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: tmp
        - name: kube-api-access-fzss8
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
