apiVersion: v1
kind: Pod
metadata:
    generateName: git-sync-test-
    labels:
        app: git-sync
        batch.kubernetes.io/controller-uid: 4f433793-50de-4b2e-839f-fa73e8b5b37e
        batch.kubernetes.io/job-name: git-sync-test
        component: test-job
        controller-uid: 4f433793-50de-4b2e-839f-fa73e8b5b37e
        job-name: git-sync-test
    name: git-sync-test-lsw8b
    namespace: test-backup
    ownerReferences:
        - apiVersion: batch/v1
          blockOwnerDeletion: true
          controller: true
          kind: Job
          name: git-sync-test
          uid: 4f433793-50de-4b2e-839f-fa73e8b5b37e
spec:
    containers:
        - env:
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                    key: minio-endpoint
                    name: git-sync-secrets
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                    key: minio-bucket
                    name: git-sync-secrets
            - name: MINIO_USE_SSL
              valueFrom:
                secretKeyRef:
                    key: minio-use-ssl
                    name: git-sync-secrets
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-access-key
                    name: git-sync-secrets
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                    key: minio-secret-key
                    name: git-sync-secrets
            - name: GIT_REPOSITORY
              valueFrom:
                secretKeyRef:
                    key: git-repository
                    name: git-sync-secrets
            - name: GIT_BRANCH
              valueFrom:
                secretKeyRef:
                    key: git-branch
                    name: git-sync-secrets
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                    key: git-username
                    name: git-sync-secrets
            - name: GIT_EMAIL
              valueFrom:
                secretKeyRef:
                    key: git-email
                    name: git-sync-secrets
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                    key: git-token
                    name: git-sync-secrets
            - name: WORK_DIR
              valueFrom:
                secretKeyRef:
                    key: work-dir
                    name: git-sync-secrets
            - name: RETRY_ATTEMPTS
              valueFrom:
                secretKeyRef:
                    key: retry-attempts
                    name: git-sync-secrets
            - name: RETRY_DELAY
              valueFrom:
                secretKeyRef:
                    key: retry-delay
                    name: git-sync-secrets
          image: git-sync:alpine-production
          imagePullPolicy: Never
          name: git-sync
          resources:
            limits:
                cpu: "1"
                memory: 1Gi
            requests:
                cpu: 200m
                memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /workspace
              name: workspace
            - mountPath: /home/git-sync-user
              name: home
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-9crfw
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
    serviceAccount: cluster-backup
    serviceAccountName: cluster-backup
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: workspace
        - emptyDir: {}
          name: home
        - name: kube-api-access-9crfw
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
