apiVersion: v1
kind: Pod
metadata:
    generateName: git-sync-minimal-test-
    labels:
        app: git-sync
        batch.kubernetes.io/controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
        batch.kubernetes.io/job-name: git-sync-minimal-test
        component: minimal-test
        controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
        job-name: git-sync-minimal-test
    name: git-sync-minimal-test-5rv5d
    namespace: test-backup
    ownerReferences:
        - apiVersion: batch/v1
          blockOwnerDeletion: true
          controller: true
          kind: Job
          name: git-sync-minimal-test
          uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
spec:
    containers:
        - args:
            - -c
            - echo 'Testing git-sync environment' && echo 'WORK_DIR='$WORK_DIR && echo 'MINIO_ENDPOINT='$MINIO_ENDPOINT && ls -la /workspace && mkdir -p /workspace/test-dir && ls -la /workspace && echo 'Test completed successfully'
          command:
            - /bin/sh
          env:
            - name: WORK_DIR
              valueFrom:
                secretKeyRef:
                    key: work-dir
                    name: git-sync-secrets
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                    key: minio-endpoint
                    name: git-sync-secrets
          image: alpine:latest
          imagePullPolicy: Always
          name: git-sync-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /workspace
              name: workspace
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-hzb8w
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
    serviceAccount: cluster-backup
    serviceAccountName: cluster-backup
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: workspace
        - name: kube-api-access-hzb8w
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
