apiVersion: v1
kind: Service
metadata:
    annotations:
        meta.helm.sh/release-name: harbor
        meta.helm.sh/release-namespace: harbor
    labels:
        app: harbor
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: harbor
        app.kubernetes.io/part-of: harbor
        app.kubernetes.io/version: 2.13.1
        chart: harbor
        heritage: Helm
        release: harbor
    name: harbor
    namespace: harbor
spec:
    clusterIP: 10.103.94.70
    clusterIPs:
        - 10.103.94.70
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: http
          nodePort: 30002
          port: 80
          protocol: TCP
          targetPort: 8080
    selector:
        app: harbor
        component: nginx
        release: harbor
    sessionAffinity: None
    type: NodePort
