---
apiVersion: v1
kind: Pod
metadata:
  name: check-minio-backups
  namespace: test-backup
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  containers:
  - name: minio-check
    image: minio/mc:latest
    command: ["/bin/sh"]
    args: ["-c", "echo 'Configuring MinIO client...'; mc alias set myminio http://$MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY; echo 'Listing bucket contents...'; mc ls myminio/$MINIO_BUCKET --recursive | head -20; echo 'Total files:'; mc ls myminio/$MINIO_BUCKET --recursive | wc -l"]
    env:
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-endpoint
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-access-key
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-secret-key
    - name: MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-bucket