---
apiVersion: v1
kind: Pod
metadata:
  name: debug-git-sync
  namespace: test-backup
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: debug
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "env | grep -E '(WORK|MINIO|GIT)' && ls -la /workspace && sleep 300"]
    env:
    - name: WORK_DIR
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: work-dir
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-endpoint
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}