---
apiVersion: v1
kind: Pod
metadata:
  name: debug-git-sync-env
  namespace: test-backup
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: debug
    image: git-sync:alpine-production
    command: ["/bin/sh"]
    args: ["-c", "echo 'Environment:'; env | grep -E '(WORK|MINIO|GIT)'; echo 'PWD:'; pwd; echo 'Workspace:'; ls -la /workspace; echo 'Testing path logic:'; echo $WORK_DIR; echo 'filepath.Join test would create:'; sleep 300"]
    env:
    - name: WORK_DIR
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: work-dir
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-endpoint
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}