---
apiVersion: v1
kind: Pod
metadata:
  name: debug-git-sync-binary
  namespace: test-backup
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: debug
    image: git-sync:alpine-production
    command: ["/bin/sh"]
    args: ["-c", "echo 'Testing git-sync binary:'; echo 'Binary location:'; which git-sync; echo 'Binary info:'; ls -la /usr/local/bin/git-sync; echo 'Testing health check:'; /usr/local/bin/git-sync --health-check; echo 'Environment:'; env | grep -E '(WORK|MINIO|GIT)'; sleep 600"]
    env:
    - name: WORK_DIR
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: work-dir
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-endpoint
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-access-key
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-secret-key
    - name: MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-bucket
    - name: MINIO_USE_SSL
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-use-ssl
    - name: GIT_REPOSITORY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-repository
    - name: GIT_BRANCH
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-branch
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-username
    - name: GIT_EMAIL
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-email
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-token
    - name: RETRY_ATTEMPTS
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: retry-attempts
    - name: RETRY_DELAY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: retry-delay
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}