---
apiVersion: v1
kind: Pod
metadata:
  name: debug-git-sync-detailed
  namespace: test-backup
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: debug
    image: git-sync:v3-https-fix
    command: ["/bin/sh"]
    args: ["-c", "echo 'Testing MinIO connectivity...'; echo 'Environment variables:'; env | grep -E '(MINIO|GIT)' | grep -v SECRET_KEY | grep -v TOKEN; echo 'Starting git-sync in debug mode...'; /usr/local/bin/git-sync || echo 'Git sync failed, checking workspace...'; echo 'Work directory contents:'; ls -la /tmp/git-sync-work/ 2>/dev/null || echo 'Work dir not found'; echo 'Repository contents:'; ls -la /tmp/git-sync-work/repository/ 2>/dev/null || echo 'Repo dir not found'; echo 'Backup contents:'; ls -la /tmp/git-sync-work/backups/ 2>/dev/null || echo 'Backup dir not found'"]
    env:
    - name: MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-endpoint
    - name: MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-bucket
    - name: MINIO_USE_SSL
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-use-ssl
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-access-key
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: minio-secret-key
    - name: GIT_REPOSITORY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-repository
    - name: GIT_BRANCH
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-branch
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-username
    - name: GIT_EMAIL
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-email
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: git-token
    - name: WORK_DIR
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: work-dir
    - name: RETRY_ATTEMPTS
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: retry-attempts
    - name: RETRY_DELAY
      valueFrom:
        secretKeyRef:
          name: git-sync-secrets
          key: retry-delay