version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-test
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 admin admin123456;
      /usr/bin/mc mb myminio/cluster-backups --ignore-existing;
      /usr/bin/mc policy set public myminio/cluster-backups;
      echo 'MinIO setup complete';
      "
    volumes:
      - minio_data:/data

volumes:
  minio_data: