---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: test-backup
  labels:
    app: cluster-backup
    component: config
data:
  # Basic Configuration
  batch-size: "50"
  retry-attempts: "3"
  retry-delay: "5s"
  
  # Resource Filtering Configuration
  # Filtering mode: "whitelist", "blacklist", "hybrid"
  # - whitelist: Only include-resources are backed up (current behavior)  
  # - blacklist: All resources except exclude-resources are backed up
  # - hybrid: Include list + exclude list both applied
  filtering-mode: "blacklist"
  
  # Include specific resource types (comma-separated)
  # Only used in "whitelist" and "hybrid" modes
  include-resources: |
    pods,services,deployments,replicasets,configmaps,secrets,
    persistentvolumes,persistentvolumeclaims,serviceaccounts,
    roles,rolebindings,clusterroles,clusterrolebindings,
    ingresses,networkpolicies,jobs,cronjobs,daemonsets,statefulsets,
    routes.route.openshift.io,buildconfigs.build.openshift.io,
    imagestreams.image.openshift.io,deploymentconfigs.apps.openshift.io

  # Exclude specific resource types (comma-separated)
  # Used in "blacklist" and "hybrid" modes 
  exclude-resources: |
    events,nodes,endpoints,replicationcontrollers

  # Include specific namespaces (comma-separated, empty = all non-system)
  include-namespaces: |
    
  # Exclude specific namespaces (comma-separated)
  exclude-namespaces: |
    kube-system,kube-public,kube-node-lease,openshift-system,
    openshift-cluster-version,openshift-machine-api,openshift-kube-apiserver,
    openshift-kube-controller-manager,openshift-kube-scheduler,openshift-etcd,
    openshift-apiserver,openshift-controller-manager,openshift-service-ca,
    openshift-network-operator,openshift-sdn,openshift-dns,openshift-ingress,
    openshift-authentication,openshift-oauth-apiserver,openshift-image-registry,
    openshift-cluster-storage-operator,openshift-cluster-csi-drivers,
    openshift-monitoring,openshift-operator-lifecycle-manager,
    openshift-marketplace,openshift-console,openshift-console-operator

  # Custom Resource Definitions (CRDs) to include
  include-crds: |
    workflows.argoproj.io,workflowtemplates.argoproj.io,
    clusterworkflowtemplates.argoproj.io,cronworkflows.argoproj.io,
    eventsources.argoproj.io,sensors.argoproj.io,eventbus.argoproj.io,
    applications.argoproj.io,appprojects.argoproj.io,
    destinationrules.networking.istio.io,virtualservices.networking.istio.io,
    gateways.networking.istio.io,serviceentries.networking.istio.io,
    certificates.cert-manager.io,clusterissuers.cert-manager.io,
    helmreleases.helm.toolkit.fluxcd.io,gitrepositories.source.toolkit.fluxcd.io

  # Advanced Filtering
  # Include only resources with specific labels (label-selector format)
  label-selector: ""
  
  # Include only resources with specific annotations
  annotation-selector: ""
  
  # Resource size limits (skip resources larger than this)
  max-resource-size: "10MB"
  
  # Backup behavior
  follow-owner-references: "true"
  include-managed-fields: "false"
  include-status: "false"
  
  # OpenShift specific settings
  openshift-mode: "auto-detect"  # auto-detect, enabled, disabled
  include-openshift-resources: "true"
  
  # Backup validation
  validate-yaml: "true"
  skip-invalid-resources: "true"