---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync
  namespace: openshift-backup
  labels:
    app: git-sync
    component: git-sync-cronjob
spec:
  schedule: "0 4 * * *"  # Daily at 4 AM (2 hours after backup)
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 1800  # 30 minutes
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            app: git-sync
            component: git-sync-job
        spec:
          serviceAccountName: git-sync
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: git-sync
            image: registry.redhat.io/ubi9/ubi:latest
            imagePullPolicy: Always
            command:
            - /usr/local/bin/git-sync
            env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: git-sync-config
                  key: minio-endpoint
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: git-sync-config
                  key: minio-bucket
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: git-sync-config
                  key: minio-use-ssl
            - name: GIT_REPOSITORY
              valueFrom:
                configMapKeyRef:
                  name: git-sync-config
                  key: git-repository
            - name: GIT_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: git-sync-config
                  key: git-branch
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-secret-key
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-username
            - name: GIT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-email
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-token
                  optional: true
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: work-dir
              mountPath: /workspace
            - name: ssh-key
              mountPath: /etc/git-secrets
              readOnly: true
            - name: git-config
              mountPath: /etc/gitconfig
              readOnly: true
            ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          volumes:
          - name: tmp
            emptyDir: {}
          - name: work-dir
            emptyDir:
              sizeLimit: 10Gi
          - name: ssh-key
            secret:
              secretName: git-sync-secrets
              items:
              - key: ssh-private-key
                path: ssh-private-key
                mode: 0600
              defaultMode: 0600
          - name: git-config
            configMap:
              name: git-sync-config
              items:
              - key: gitconfig
                path: gitconfig
          tolerations:
          - operator: Exists
            effect: NoSchedule
          - operator: Exists
            effect: NoExecute
          nodeSelector:
            kubernetes.io/os: linux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-sync
  namespace: openshift-backup
  labels:
    app: git-sync
    component: service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-sync-config
  namespace: openshift-backup
  labels:
    app: git-sync
    component: configuration
data:
  minio-endpoint: "minio.backup.example.com:9000"
  minio-bucket: "cluster-backups"
  minio-use-ssl: "true"
  git-repository: "git@github.com:your-org/cluster-backups.git"  # Change this
  git-branch: "main"
  work-dir: "/workspace"
  gitconfig: |
    [user]
        name = cluster-backup
        email = cluster-backup@example.com
    [init]
        defaultBranch = main
    [safe]
        directory = *
    [core]
        sshCommand = ssh -i /etc/git-secrets/ssh-private-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
---
apiVersion: v1
kind: Service
metadata:
  name: git-sync-metrics
  namespace: openshift-backup
  labels:
    app: git-sync
    component: metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: git-sync
    component: git-sync-job
  type: ClusterIP