---
apiVersion: batch/v1
kind: Job
metadata:
  name: git-sync-test
  namespace: test-backup
  labels:
    app: git-sync
    component: test-job
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600  # 10 minutes
  template:
    metadata:
      labels:
        app: git-sync
        component: test-job
    spec:
      serviceAccountName: cluster-backup  # Reuse existing service account
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: git-sync
        image: git-sync:v3-https-fix
        imagePullPolicy: Never
        env:
        # MinIO Configuration
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: minio-endpoint
        - name: MINIO_BUCKET
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: minio-bucket
        - name: MINIO_USE_SSL
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: minio-use-ssl
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: minio-secret-key
        # Git Configuration
        - name: GIT_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: git-repository
        - name: GIT_BRANCH
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: git-branch
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: git-username
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: git-email
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: git-token
        # Additional Configuration
        - name: WORK_DIR
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: work-dir
        - name: RETRY_ATTEMPTS
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: retry-attempts
        - name: RETRY_DELAY
          valueFrom:
            secretKeyRef:
              name: git-sync-secrets
              key: retry-delay
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # Git needs to write files
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: workspace
          mountPath: /workspace
        - name: home
          mountPath: /home/git-sync-user
      volumes:
      - name: tmp
        emptyDir: {}
      - name: workspace
        emptyDir: {}
      - name: home
        emptyDir: {}