---
apiVersion: v1
kind: Pod
metadata:
  name: backup-test
  namespace: test-backup
  labels:
    app: cluster-backup
    component: test
spec:
  serviceAccountName: cluster-backup
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: backup
    image: golang:1.21-alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]
    env:
    - name: CLUSTER_DOMAIN
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: cluster-domain
    - name: CLUSTER_NAME
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: cluster-name
    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: minio-endpoint
    - name: MINIO_BUCKET
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: minio-bucket
    - name: MINIO_USE_SSL
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: minio-use-ssl
    - name: EXCLUDE_NAMESPACES
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: exclude-namespaces
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: backup-secrets
          key: minio-access-key
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: backup-secrets
          key: minio-secret-key
    - name: LOG_LEVEL
      value: "debug"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: workdir
      mountPath: /workspace
  volumes:
  - name: tmp
    emptyDir: {}
  - name: workdir
    emptyDir: {}