apiVersion: apps/v1
kind: Deployment
metadata:
    annotations: {}
    name: controller-manager
    namespace: argo-events
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: controller-manager
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: controller-manager
        spec:
            containers:
                - args:
                    - controller
                  env:
                    - name: ARGO_EVENTS_IMAGE
                      value: quay.io/argoproj/argo-events:v1.9.6
                    - name: NAMESPACE
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                  image: quay.io/argoproj/argo-events:v1.9.6
                  imagePullPolicy: Always
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /healthz
                        port: 8081
                        scheme: HTTP
                    initialDelaySeconds: 3
                    periodSeconds: 3
                    successThreshold: 1
                    timeoutSeconds: 1
                  name: controller-manager
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /readyz
                        port: 8081
                        scheme: HTTP
                    initialDelaySeconds: 3
                    periodSeconds: 3
                    successThreshold: 1
                    timeoutSeconds: 1
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /etc/argo-events
                      name: controller-config-volume
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
                runAsUser: 9731
            serviceAccount: argo-events-sa
            serviceAccountName: argo-events-sa
            terminationGracePeriodSeconds: 30
            volumes:
                - configMap:
                    defaultMode: 420
                    name: argo-events-controller-config
                  name: controller-config-volume
