---
# Minimal OpenShift CronJob for cluster backup
# Works with default ServiceAccount and restricted-v2 SCC
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-backup-minimal
  namespace: backup-system
  labels:
    app: cluster-backup
    component: backup-cronjob
    platform: openshift
    version: minimal
  annotations:
    description: "Minimal OpenShift cluster backup job using default ServiceAccount"
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 7200  # 2 hours timeout
      template:
        metadata:
          labels:
            app: cluster-backup
            component: backup-job
            platform: openshift
            version: minimal
        spec:
          # Use default ServiceAccount (implicit)
          restartPolicy: OnFailure
          # No securityContext needed - OpenShift will assign automatically
          containers:
          - name: backup
            image: registry.example.com/openshift/cluster-backup:latest
            imagePullPolicy: Always
            env:
            # All configuration comes from backup-secrets
            - name: CLUSTER_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: cluster-domain
            - name: CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: cluster-name
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-endpoint
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-bucket
            - name: MINIO_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-use-ssl
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: minio-secret-key
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: log-level
            # Cleanup configuration
            - name: ENABLE_CLEANUP
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: enable-cleanup
                  optional: true
            - name: RETENTION_DAYS
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: retention-days
                  optional: true
            - name: CLEANUP_ON_STARTUP
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: cleanup-on-startup
                  optional: true
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            # Minimal security context - let OpenShift handle the rest
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: workspace
              mountPath: /workspace
            - name: data
              mountPath: /data
            ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            # Simple readiness probe
            readinessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          volumes:
          - name: tmp
            emptyDir: {}
          - name: workspace
            emptyDir: {}
          - name: data
            emptyDir: {}
          # Minimal node selection
          nodeSelector:
            kubernetes.io/os: linux