---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  namespace: backup-system
  labels:
    app: cluster-backup
    component: backup-service
    platform: openshift
  annotations:
    description: "Configuration secrets for OpenShift cluster backup service"
type: Opaque
stringData:
  # Cluster Configuration
  cluster-domain: "cluster.local"
  cluster-name: "my-openshift-cluster"
  
  # MinIO Configuration
  minio-endpoint: "minio.example.com:9000"
  minio-bucket: "cluster-backups"
  minio-use-ssl: "true"
  minio-access-key: "your-access-key"
  minio-secret-key: "your-secret-key"
  
  # Backup Configuration
  exclude-namespaces: |
    openshift-*
    kube-*
    default
  batch-size: "50"
  retry-attempts: "3"
  retry-delay: "5s"
  log-level: "info"
  
  # Cleanup Configuration (NEW)
  enable-cleanup: "true"
  retention-days: "7"
  cleanup-on-startup: "false"