---
# ServiceMonitor for Prometheus Operator in OpenShift
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-backup-metrics
  namespace: backup-system
  labels:
    app: cluster-backup
    component: monitoring
    platform: openshift
  annotations:
    description: "Prometheus monitoring for OpenShift cluster backup service"
spec:
  selector:
    matchLabels:
      app: cluster-backup
      component: backup-service
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
    - backup-system
---
# Service for metrics endpoint
apiVersion: v1
kind: Service
metadata:
  name: cluster-backup-metrics
  namespace: backup-system
  labels:
    app: cluster-backup
    component: backup-service
    platform: openshift
  annotations:
    description: "Metrics service for OpenShift cluster backup"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cluster-backup
    component: backup-job
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-backup-alerts
  namespace: backup-system
  labels:
    app: cluster-backup
    component: monitoring
    platform: openshift
    prometheus: kube-prometheus
    role: alert-rules
  annotations:
    description: "Alerting rules for OpenShift cluster backup service"
spec:
  groups:
  - name: cluster-backup.rules
    rules:
    - alert: OpenShiftBackupJobFailed
      expr: increase(cluster_backup_errors_total[1h]) > 0
      for: 5m
      labels:
        severity: critical
        service: cluster-backup
        platform: openshift
      annotations:
        summary: "OpenShift Backup Job Failed"
        description: "Backup job has failed {{ $value }} times in the last hour"
        
    - alert: OpenShiftBackupJobNotRunning
      expr: time() - cluster_backup_last_success_timestamp > 86400
      for: 5m
      labels:
        severity: warning
        service: cluster-backup
        platform: openshift
      annotations:
        summary: "OpenShift Backup Job Not Running"
        description: "No successful backup in the last 24 hours"
        
    - alert: OpenShiftBackupHighDuration
      expr: cluster_backup_duration_seconds > 3600
      for: 2m
      labels:
        severity: warning
        service: cluster-backup
        platform: openshift
      annotations:
        summary: "OpenShift Backup Taking Too Long"
        description: "Backup took {{ $value }} seconds to complete"
        
    - alert: OpenShiftBackupCleanupFailed
      expr: increase(cluster_backup_cleanup_errors_total[1h]) > 0
      for: 5m
      labels:
        severity: warning
        service: cluster-backup
        platform: openshift
      annotations:
        summary: "OpenShift Backup Cleanup Failed"
        description: "Backup cleanup failed {{ $value }} times in the last hour"