---
# OpenShift ClusterRole for default ServiceAccount
# This allows the backup system to work with OpenShift's default ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-backup-default-sa-reader
  labels:
    app: cluster-backup
    component: backup-service
    platform: openshift
rules:
# All API groups and resources - read only access
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for default ServiceAccount in backup-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-backup-default-sa-binding
  labels:
    app: cluster-backup
    component: backup-service
    platform: openshift
subjects:
- kind: ServiceAccount
  name: default
  namespace: backup-system
roleRef:
  kind: ClusterRole
  name: cluster-backup-default-sa-reader
  apiGroup: rbac.authorization.k8s.io