---
# SecurityContextConstraints for backup service in OpenShift
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: backup-scc
  labels:
    app: cluster-backup
    component: security
    platform: openshift
  annotations:
    description: "Security context constraints for cluster backup service"
    kubernetes.io/description: "Provides the minimum required security for backup operations"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
allowedUnsafeSysctls: []
defaultAddCapabilities: []
defaultAllowPrivilegeEscalation: false
forbiddenSysctls:
  - "*"
# File system group strategy
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1001
    max: 1001
# Read-only root filesystem
readOnlyRootFilesystem: true
# Required drop capabilities
requiredDropCapabilities:
- ALL
# Run as user strategy
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1001
  uidRangeMax: 1001
# SELinux context strategy
seLinuxContext:
  type: MustRunAs
# Supplemental groups strategy
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: 1001
    max: 1001
# Allowed volume types
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
# Users and groups that can use this SCC
users:
- system:serviceaccount:backup-system:default
groups: []
priority: 10