---
# Minimal ClusterRole for OpenShift backup with default ServiceAccount
# Only includes essential permissions for reading cluster resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-minimal-reader
  labels:
    app: cluster-backup
    component: minimal-rbac
    platform: openshift
rules:
# All API groups and resources - read only access
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for default ServiceAccount in backup-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-minimal-binding
  labels:
    app: cluster-backup
    component: minimal-rbac
    platform: openshift
subjects:
- kind: ServiceAccount
  name: default
  namespace: backup-system
roleRef:
  kind: ClusterRole
  name: backup-minimal-reader
  apiGroup: rbac.authorization.k8s.io