apiVersion: v1
kind: Pod
metadata:
    generateName: controller-manager-574bd84977-
    labels:
        app: controller-manager
        pod-template-hash: 574bd84977
    name: controller-manager-574bd84977-bg887
    namespace: argo-events
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: controller-manager-574bd84977
          uid: 475679e2-3fbc-41cf-b507-13253317850c
spec:
    containers:
        - args:
            - controller
          env:
            - name: ARGO_EVENTS_IMAGE
              value: quay.io/argoproj/argo-events:v1.9.6
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          image: quay.io/argoproj/argo-events:v1.9.6
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /healthz
                port: 8081
                scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: controller-manager
          readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /readyz
                port: 8081
                scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/argo-events
              name: controller-config-volume
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-ftkfq
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
        runAsNonRoot: true
        runAsUser: 9731
    serviceAccount: argo-events-sa
    serviceAccountName: argo-events-sa
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - configMap:
            defaultMode: 420
            name: argo-events-controller-config
          name: controller-config-volume
        - name: kube-api-access-ftkfq
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
