apiVersion: v1
kind: Pod
metadata:
    generateName: eventbus-default-stan-
    labels:
        apps.kubernetes.io/pod-index: "0"
        controller: eventbus-controller
        controller-revision-hash: eventbus-default-stan-787bc9645c
        eventbus-name: default
        owner-name: default
        statefulset.kubernetes.io/pod-name: eventbus-default-stan-0
    name: eventbus-default-stan-0
    namespace: argo-events
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: StatefulSet
          name: eventbus-default-stan
          uid: c0966c54-9631-4e32-b844-f5c8dd249768
spec:
    containers:
        - command:
            - /nats-streaming-server
            - -sc
            - /etc/stan-config/stan.conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
            - name: CLUSTER_ADVERTISE
              value: $(POD_NAME).eventbus-default-stan-svc.$(POD_NAMESPACE).svc
          image: nats-streaming:0.22.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /
                port: 8222
                scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: stan
          ports:
            - containerPort: 4222
              name: client
              protocol: TCP
            - containerPort: 6222
              name: cluster
              protocol: TCP
            - containerPort: 8222
              name: monitor
              protocol: TCP
          resources:
            requests:
                cpu: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/stan-config
              name: config-volume
            - mountPath: /data/stan
              name: stan-data
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-q4j8v
              readOnly: true
        - args:
            - -connz
            - -routez
            - -subz
            - -varz
            - -channelz
            - -serverz
            - http://localhost:8222
          image: natsio/prometheus-nats-exporter:0.8.0
          imagePullPolicy: IfNotPresent
          name: metrics
          ports:
            - containerPort: 7777
              name: metrics
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-q4j8v
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: eventbus-default-stan-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: eventbus-default-stan-svc
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: config-volume
          projected:
            defaultMode: 420
            sources:
                - configMap:
                    items:
                        - key: stan-config
                          path: stan.conf
                    name: eventbus-default-stan-configmap
                - secret:
                    items:
                        - key: auth
                          path: auth.conf
                    name: eventbus-default-server
        - emptyDir: {}
          name: stan-data
        - name: kube-api-access-q4j8v
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
