apiVersion: apps/v1
kind: ReplicaSet
metadata:
    annotations:
        deployment.kubernetes.io/desired-replicas: "3"
        deployment.kubernetes.io/max-replicas: "4"
    labels:
        app: buildkitd
        pod-template-hash: 86b5ff8c8f
    name: buildkitd-86b5ff8c8f
    namespace: buildkit
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: buildkitd
          uid: a9690719-8109-4b6e-bae7-f4c674537d95
spec:
    replicas: 3
    selector:
        matchLabels:
            app: buildkitd
            pod-template-hash: 86b5ff8c8f
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: buildkitd
                pod-template-hash: 86b5ff8c8f
        spec:
            containers:
                - args:
                    - --addr=tcp://0.0.0.0:1234
                  command:
                    - buildkitd
                  image: moby/buildkit:latest
                  imagePullPolicy: Always
                  name: buildkitd
                  ports:
                    - containerPort: 1234
                      name: tcp
                      protocol: TCP
                  resources:
                    limits:
                        cpu: "2"
                        memory: 4Gi
                    requests:
                        cpu: 200m
                        memory: 512Mi
                  securityContext:
                    privileged: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /run/buildkit
                      name: buildkit-sock
                    - mountPath: /var/lib/buildkit
                      name: buildkit-cache
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: buildkit-sock
                - emptyDir: {}
                  name: buildkit-cache
