apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: buildkitd-external
    name: buildkitd-external
    namespace: buildkit
spec:
    clusterIP: 10.106.117.228
    clusterIPs:
        - 10.106.117.228
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - name: tcp
          port: 1234
          protocol: TCP
          targetPort: 1234
    selector:
        app: buildkitd
    sessionAffinity: None
    type: ClusterIP
