apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: default-argo-access
    namespace: build-pipeline
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: argo-cluster-role
subjects:
    - kind: ServiceAccount
      name: default
      namespace: build-pipeline
