apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations: {}
    name: workflow-rolebinding
    namespace: build-pipeline
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: workflow-role
subjects:
    - kind: ServiceAccount
      name: workflow-service-account
      namespace: build-pipeline
