apiVersion: apps/v1
kind: ReplicaSet
metadata:
    annotations:
        deployment.kubernetes.io/desired-replicas: "2"
        deployment.kubernetes.io/max-replicas: "3"
    labels:
        app: build-status-service
        component: backend
        pod-template-hash: 64f8c5fc74
        tier: service
    name: build-status-service-64f8c5fc74
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: build-status-service
          uid: b43fe0df-9c75-4033-999b-08effb4c9fb9
spec:
    replicas: 0
    selector:
        matchLabels:
            app: build-status-service
            pod-template-hash: 64f8c5fc74
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: build-status-service
                component: backend
                pod-template-hash: 64f8c5fc74
                tier: service
        spec:
            containers:
                - env:
                    - name: PORT
                      value: "8080"
                    - name: MINIO_ENDPOINT
                      value: host.minikube.internal:9000
                    - name: MINIO_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                            key: access-key
                            name: minio-credentials
                    - name: MINIO_SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                            key: secret-key
                            name: minio-credentials
                    - name: MINIO_BUCKET
                      value: builds
                    - name: MINIO_USE_SSL
                      value: "false"
                    - name: LOG_LEVEL
                      value: info
                    - name: GIN_MODE
                      value: release
                  image: 10.103.94.70/library/build-status-service:latest
                  imagePullPolicy: Always
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /health
                        port: 8080
                        scheme: HTTP
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    successThreshold: 1
                    timeoutSeconds: 5
                  name: build-status-service
                  ports:
                    - containerPort: 8080
                      name: http
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /health
                        port: 8080
                        scheme: HTTP
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    successThreshold: 1
                    timeoutSeconds: 3
                  resources:
                    limits:
                        cpu: 200m
                        memory: 256Mi
                    requests:
                        cpu: 100m
                        memory: 128Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsGroup: 1001
                    runAsNonRoot: true
                    runAsUser: 1001
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
