apiVersion: apps/v1
kind: ReplicaSet
metadata:
    annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        resource-spec-hash: "861519892"
    labels:
        controller: sensor-controller
        owner-name: build-webhook-sensor
        pod-template-hash: 8575d4975d
        sensor-name: build-webhook-sensor
    name: build-webhook-sensor-sensor-6wg7t-8575d4975d
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: build-webhook-sensor-sensor-6wg7t
          uid: 0d335c66-bab5-4535-a9d5-d9871d9da6c4
spec:
    replicas: 1
    selector:
        matchLabels:
            controller: sensor-controller
            owner-name: build-webhook-sensor
            pod-template-hash: 8575d4975d
            sensor-name: build-webhook-sensor
    template:
        metadata:
            creationTimestamp: null
            labels:
                controller: sensor-controller
                owner-name: build-webhook-sensor
                pod-template-hash: 8575d4975d
                sensor-name: build-webhook-sensor
        spec:
            containers:
                - args:
                    - sensor-service
                  env:
                    - name: SENSOR_OBJECT
                      value: eyJtZXRhZGF0YSI6eyJuYW1lIjoiYnVpbGQtd2ViaG9vay1zZW5zb3IiLCJuYW1lc3BhY2UiOiJidWlsZC1waXBlbGluZSIsImNyZWF0aW9uVGltZXN0YW1wIjpudWxsfSwic3BlYyI6eyJkZXBlbmRlbmNpZXMiOlt7Im5hbWUiOiJidWlsZC10cmlnZ2VyIiwiZXZlbnRTb3VyY2VOYW1lIjoiYnVpbGQtd2ViaG9vayIsImV2ZW50TmFtZSI6ImJ1aWxkLXRyaWdnZXIifV0sInRyaWdnZXJzIjpbeyJ0ZW1wbGF0ZSI6eyJuYW1lIjoiYnVpbGQtd29ya2Zsb3ctdHJpZ2dlciIsImFyZ29Xb3JrZmxvdyI6eyJzb3VyY2UiOnsicmVzb3VyY2UiOnsiYXBpVmVyc2lvbiI6ImFyZ29wcm9qLmlvL3YxYWxwaGExIiwia2luZCI6IldvcmtmbG93IiwibWV0YWRhdGEiOnsiZ2VuZXJhdGVOYW1lIjoiYnVpbGQtIiwibmFtZXNwYWNlIjoiYnVpbGQtcGlwZWxpbmUifSwic3BlYyI6eyJhcmd1bWVudHMiOnsicGFyYW1ldGVycyI6W3sibmFtZSI6InJlcG9fdXJsIiwidmFsdWUiOiJodHRwczovL2dpdGh1Yi5jb20vbmdpbngvbmdpbnguZ2l0In0seyJuYW1lIjoiYnJhbmNoIiwidmFsdWUiOiJtYXN0ZXIifSx7Im5hbWUiOiJkb2NrZXJmaWxlX3BhdGgiLCJ2YWx1ZSI6IkRvY2tlcmZpbGUifSx7Im5hbWUiOiJpbWFnZV9uYW1lIiwidmFsdWUiOiJsb2NhbGhvc3Qvd2ViaG9vay10ZXN0In0seyJuYW1lIjoiaW1hZ2VfdGFnIiwidmFsdWUiOiJsYXRlc3QifSx7Im5hbWUiOiJidWlsZF9pZCIsInZhbHVlIjoiYnVpbGQtdW5rbm93biJ9XX0sInNlcnZpY2VBY2NvdW50TmFtZSI6IndvcmtmbG93LXNlcnZpY2UtYWNjb3VudCIsIndvcmtmbG93VGVtcGxhdGVSZWYiOnsibmFtZSI6ImJ1aWxkLXdvcmtmbG93LXRlbXBsYXRlIn19fX0sIm9wZXJhdGlvbiI6InN1Ym1pdCIsInBhcmFtZXRlcnMiOlt7InNyYyI6eyJkZXBlbmRlbmN5TmFtZSI6ImJ1aWxkLXRyaWdnZXIiLCJkYXRhS2V5IjoiYm9keS5yZXBvX3VybCJ9LCJkZXN0Ijoic3BlYy5hcmd1bWVudHMucGFyYW1ldGVycy4wLnZhbHVlIn0seyJzcmMiOnsiZGVwZW5kZW5jeU5hbWUiOiJidWlsZC10cmlnZ2VyIiwiZGF0YUtleSI6ImJvZHkuYnJhbmNoIn0sImRlc3QiOiJzcGVjLmFyZ3VtZW50cy5wYXJhbWV0ZXJzLjEudmFsdWUifSx7InNyYyI6eyJkZXBlbmRlbmN5TmFtZSI6ImJ1aWxkLXRyaWdnZXIiLCJkYXRhS2V5IjoiYm9keS5kb2NrZXJmaWxlX3BhdGgifSwiZGVzdCI6InNwZWMuYXJndW1lbnRzLnBhcmFtZXRlcnMuMi52YWx1ZSJ9LHsic3JjIjp7ImRlcGVuZGVuY3lOYW1lIjoiYnVpbGQtdHJpZ2dlciIsImRhdGFLZXkiOiJib2R5LmltYWdlX25hbWUifSwiZGVzdCI6InNwZWMuYXJndW1lbnRzLnBhcmFtZXRlcnMuMy52YWx1ZSJ9LHsic3JjIjp7ImRlcGVuZGVuY3lOYW1lIjoiYnVpbGQtdHJpZ2dlciIsImRhdGFLZXkiOiJib2R5LmltYWdlX3RhZyJ9LCJkZXN0Ijoic3BlYy5hcmd1bWVudHMucGFyYW1ldGVycy40LnZhbHVlIn0seyJzcmMiOnsiZGVwZW5kZW5jeU5hbWUiOiJidWlsZC10cmlnZ2VyIiwiZGF0YUtleSI6ImJvZHkuYnVpbGRfaWQifSwiZGVzdCI6InNwZWMuYXJndW1lbnRzLnBhcmFtZXRlcnMuNS52YWx1ZSJ9XX19fV0sImxvZ2dpbmdGaWVsZHMiOm51bGx9LCJzdGF0dXMiOnt9fQ==
                    - name: EVENTBUS_SUBJECT
                      value: eventbus-build-pipeline
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                    - name: LEADER_ELECTION
                    - name: EVENTBUS_CONFIG
                      value: eyJuYXRzIjp7InVybCI6Im5hdHM6Ly9ldmVudGJ1cy1kZWZhdWx0LXN0YW4tc3ZjOjQyMjIiLCJjbHVzdGVySUQiOiJldmVudGJ1cy1kZWZhdWx0IiwiYXV0aCI6Im5vbmUifX0=
                  image: quay.io/argoproj/argo-events:v1.9.6
                  imagePullPolicy: Always
                  name: main
                  ports:
                    - containerPort: 7777
                      name: metrics
                      protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: tmp
