apiVersion: v1
data:
    auth: ""
kind: Secret
metadata:
    annotations:
        resource-spec-hash: "2129581065"
        strategy: none
    labels:
        controller: eventbus-controller
        eventbus-name: default
        owner-name: default
        server-auth-secret: "yes"
    name: eventbus-default-server
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: EventBus
          name: default
          uid: 00c4fad2-b7a9-4641-87fe-1762448e8fce
type: Opaque
