apiVersion: v1
kind: Pod
metadata:
    generateName: build-management-service-fd876cddb-
    labels:
        app: build-management-service
        pod-template-hash: fd876cddb
        version: 1.0.0
    name: build-management-service-fd876cddb-2jxhb
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: build-management-service-fd876cddb
          uid: d3fc7713-ba86-427b-877c-9700e2829a23
spec:
    containers:
        - env:
            - name: PORT
              value: "8080"
            - name: BUILD_STATUS_SERVICE
              value: http://build-status-service:80
            - name: BUILD_HISTORY_SERVICE
              value: http://build-history-service:80
            - name: ARGO_WORKFLOWS_API
              value: http://argo-server.argo:2746
            - name: ARGO_EVENTS_API
              value: http://argo-events-controller.argo-events:8080
            - name: WORKFLOW_NAMESPACE
              value: build-pipeline
            - name: WORKFLOW_TEMPLATE
              value: build-workflow-template
            - name: WEBHOOK_URL
              value: http://build-webhook-service:12000/build-webhook
          image: build-management-service:v4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /api/v1/health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: build-management-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /api/v1/health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
                cpu: 500m
                memory: 512Mi
            requests:
                cpu: 100m
                memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-2t598
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: build-management-service
    serviceAccountName: build-management-service
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: kube-api-access-2t598
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
