apiVersion: v1
kind: Pod
metadata:
    generateName: build-webhook-eventsource-g9wbp-5fb65d9f84-
    labels:
        controller: eventsource-controller
        eventsource-name: build-webhook
        owner-name: build-webhook
        pod-template-hash: 5fb65d9f84
    name: build-webhook-eventsource-g9wbp-5fb65d9f84-t7wbn
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: build-webhook-eventsource-g9wbp-5fb65d9f84
          uid: 7e156615-b45e-481b-8b24-8e36dce55406
spec:
    containers:
        - args:
            - eventsource-service
          env:
            - name: EVENTSOURCE_OBJECT
              value: eyJtZXRhZGF0YSI6eyJuYW1lIjoiYnVpbGQtd2ViaG9vayIsIm5hbWVzcGFjZSI6ImJ1aWxkLXBpcGVsaW5lIiwiY3JlYXRpb25UaW1lc3RhbXAiOm51bGx9LCJzcGVjIjp7IndlYmhvb2siOnsiYnVpbGQtdHJpZ2dlciI6eyJlbmRwb2ludCI6Ii9idWlsZC13ZWJob29rIiwibWV0aG9kIjoiUE9TVCIsInBvcnQiOiIxMjAwMCIsInVybCI6IiJ9fX0sInN0YXR1cyI6e319
            - name: EVENTBUS_SUBJECT
              value: eventbus-build-pipeline
            - name: POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: LEADER_ELECTION
            - name: EVENTBUS_CONFIG
              value: eyJuYXRzIjp7InVybCI6Im5hdHM6Ly9ldmVudGJ1cy1kZWZhdWx0LXN0YW4tc3ZjOjQyMjIiLCJjbHVzdGVySUQiOiJldmVudGJ1cy1kZWZhdWx0IiwiYXV0aCI6Im5vbmUifX0=
          image: quay.io/argoproj/argo-events:v1.9.6
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 7777
              name: metrics
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-kbrnw
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: tmp
        - name: kube-api-access-kbrnw
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
