apiVersion: v1
kind: Pod
metadata:
    annotations:
        kubectl.kubernetes.io/default-container: main
        workflows.argoproj.io/node-id: build-f2sb8-1423891871
        workflows.argoproj.io/node-name: build-f2sb8.git-clone
        workflows.argoproj.io/report-outputs-completed: "true"
    labels:
        workflows.argoproj.io/completed: "false"
        workflows.argoproj.io/workflow: build-f2sb8
    name: build-f2sb8-git-clone-task-1423891871
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: Workflow
          name: build-f2sb8
          uid: 2ed9b487-84da-4f45-9744-bba95ab94eca
spec:
    containers:
        - command:
            - argoexec
            - wait
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: build-f2sb8
            - name: ARGO_WORKFLOW_UID
              value: 2ed9b487-84da-4f45-9744-bba95ab94eca
            - name: ARGO_CONTAINER_NAME
              value: wait
            - name: ARGO_TEMPLATE
              value: '{"name":"git-clone-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine/git:latest","command":["sh","-c"],"args":["git clone https://github.com/komljen/dockerfile-examples.git /workspace\ncd /workspace\ngit checkout main\nls -la\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/workspace"}]}}'
            - name: ARGO_NODE_ID
              value: build-f2sb8-1423891871
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: wait
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mainctrfs/workspace
              name: shared-workspace
            - mountPath: /tmp
              name: tmp-dir-argo
              subPath: "0"
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-v6454
              readOnly: true
        - args:
            - |
              git clone https://github.com/komljen/dockerfile-examples.git /workspace
              cd /workspace
              git checkout main
              ls -la
          command:
            - /var/run/argo/argoexec
            - emissary
            - --loglevel
            - info
            - --log-format
            - text
            - --
            - sh
            - -c
          env:
            - name: ARGO_CONTAINER_NAME
              value: main
            - name: ARGO_TEMPLATE
              value: '{"name":"git-clone-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine/git:latest","command":["sh","-c"],"args":["git clone https://github.com/komljen/dockerfile-examples.git /workspace\ncd /workspace\ngit checkout main\nls -la\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/workspace"}]}}'
            - name: ARGO_NODE_ID
              value: build-f2sb8-1423891871
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: alpine/git:latest
          imagePullPolicy: Always
          name: main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /workspace
              name: shared-workspace
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-v6454
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
        - command:
            - argoexec
            - init
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: build-f2sb8
            - name: ARGO_WORKFLOW_UID
              value: 2ed9b487-84da-4f45-9744-bba95ab94eca
            - name: ARGO_CONTAINER_NAME
              value: init
            - name: ARGO_TEMPLATE
              value: '{"name":"git-clone-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine/git:latest","command":["sh","-c"],"args":["git clone https://github.com/komljen/dockerfile-examples.git /workspace\ncd /workspace\ngit checkout main\nls -la\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/workspace"}]}}'
            - name: ARGO_NODE_ID
              value: build-f2sb8-1423891871
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-v6454
              readOnly: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: workflow-service-account
    serviceAccountName: workflow-service-account
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: var-run-argo
        - emptyDir: {}
          name: tmp-dir-argo
        - emptyDir: {}
          name: shared-workspace
        - name: kube-api-access-v6454
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
