apiVersion: v1
kind: Pod
metadata:
    generateName: build-history-service-5847849779-
    labels:
        app: build-history-service
        component: backend
        pod-template-hash: "5847849779"
        tier: service
    name: build-history-service-5847849779-rnkjs
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: build-history-service-5847849779
          uid: 4e4192a4-0163-4087-84bc-f97de220f348
spec:
    containers:
        - env:
            - name: PORT
              value: "8080"
            - name: MINIO_ENDPOINT
              value: host.minikube.internal:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                    key: access-key
                    name: minio-credentials
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                    key: secret-key
                    name: minio-credentials
            - name: MINIO_BUCKET
              value: builds
            - name: MINIO_USE_SSL
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: GIN_MODE
              value: release
          image: 10.103.94.70/library/build-history-service:latest
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /api/v1/health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: build-history-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /api/v1/health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
                cpu: 200m
                memory: 256Mi
            requests:
                cpu: 100m
                memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-txn4b
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: kube-api-access-txn4b
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
