apiVersion: v1
kind: Pod
metadata:
    annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-08T18:55:07+03:00"
    generateName: frontend-service-66645675d7-
    labels:
        app: frontend-service
        pod-template-hash: 66645675d7
        version: 1.0.0
    name: frontend-service-66645675d7-kn5rv
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: frontend-service-66645675d7
          uid: 114d1eba-f8de-4f5f-a3f2-f8366bb3f950
spec:
    containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://build-management-service.build-pipeline:80/api/v1
            - name: REACT_APP_WS_HOST
              value: build-management-service.build-pipeline
            - name: REACT_APP_WS_PORT
              value: "8080"
          image: frontend-static:v2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /health
                port: 3000
                scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: frontend-service
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /health
                port: 3000
                scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
                cpu: 200m
                memory: 256Mi
            requests:
                cpu: 50m
                memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-kphkz
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - name: kube-api-access-kphkz
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
