apiVersion: v1
kind: Pod
metadata:
    annotations:
        kubectl.kubernetes.io/default-container: main
        workflows.argoproj.io/node-id: test-buildkit-external-rkvhb-3005675458
        workflows.argoproj.io/node-name: test-buildkit-external-rkvhb.init-build-status
        workflows.argoproj.io/report-outputs-completed: "true"
    labels:
        workflows.argoproj.io/completed: "false"
        workflows.argoproj.io/workflow: test-buildkit-external-rkvhb
    name: test-buildkit-external-rkvhb-status-update-task-3005675458
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: Workflow
          name: test-buildkit-external-rkvhb
          uid: c3569cd4-fad6-4d6f-a0fe-1a5d15019d6f
spec:
    containers:
        - command:
            - argoexec
            - wait
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: test-buildkit-external-rkvhb
            - name: ARGO_WORKFLOW_UID
              value: c3569cd4-fad6-4d6f-a0fe-1a5d15019d6f
            - name: ARGO_CONTAINER_NAME
              value: wait
            - name: ARGO_TEMPLATE
              value: '{"name":"status-update-task","inputs":{"parameters":[{"name":"status","value":"started"},{"name":"message","value":"Build pipeline initiated"}]},"outputs":{},"metadata":{},"container":{"name":"","image":"curlimages/curl:latest","command":["sh","-c"],"args":["echo \"=== Status Update ===\" | tee /logs/status-update-started.log\necho \"Status: started\" | tee -a /logs/status-update-started.log\necho \"Message: Build pipeline initiated\" | tee -a /logs/status-update-started.log\necho \"Build ID: buildkit-test-$(date +%s)\" | tee -a /logs/status-update-started.log\necho \"Timestamp: $(date)\" | tee -a /logs/status-update-started.log\n\n# API call to update build status\ncurl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{\"status\":\"started\",\"message\":\"Build pipeline initiated\"}'' \\\n  \"http://build-management-service.build-pipeline:80/api/v1/builds/buildkit-test-$(date +%s)/status\" \\\n  2\u003e\u00261 | tee -a /logs/status-update-started.log\n\necho \"=== Status Update Completed ===\" | tee -a /logs/status-update-started.log\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-buildkit-external-rkvhb-3005675458
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: wait
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mainctrfs/logs
              name: shared-workspace
              subPath: logs
            - mountPath: /tmp
              name: tmp-dir-argo
              subPath: "0"
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-mvftw
              readOnly: true
        - args:
            - |
              echo "=== Status Update ===" | tee /logs/status-update-started.log
              echo "Status: started" | tee -a /logs/status-update-started.log
              echo "Message: Build pipeline initiated" | tee -a /logs/status-update-started.log
              echo "Build ID: buildkit-test-$(date +%s)" | tee -a /logs/status-update-started.log
              echo "Timestamp: $(date)" | tee -a /logs/status-update-started.log

              # API call to update build status
              curl -X PUT \
                -H "Content-Type: application/json" \
                -d '{"status":"started","message":"Build pipeline initiated"}' \
                "http://build-management-service.build-pipeline:80/api/v1/builds/buildkit-test-$(date +%s)/status" \
                2>&1 | tee -a /logs/status-update-started.log

              echo "=== Status Update Completed ===" | tee -a /logs/status-update-started.log
          command:
            - /var/run/argo/argoexec
            - emissary
            - --loglevel
            - info
            - --log-format
            - text
            - --
            - sh
            - -c
          env:
            - name: ARGO_CONTAINER_NAME
              value: main
            - name: ARGO_TEMPLATE
              value: '{"name":"status-update-task","inputs":{"parameters":[{"name":"status","value":"started"},{"name":"message","value":"Build pipeline initiated"}]},"outputs":{},"metadata":{},"container":{"name":"","image":"curlimages/curl:latest","command":["sh","-c"],"args":["echo \"=== Status Update ===\" | tee /logs/status-update-started.log\necho \"Status: started\" | tee -a /logs/status-update-started.log\necho \"Message: Build pipeline initiated\" | tee -a /logs/status-update-started.log\necho \"Build ID: buildkit-test-$(date +%s)\" | tee -a /logs/status-update-started.log\necho \"Timestamp: $(date)\" | tee -a /logs/status-update-started.log\n\n# API call to update build status\ncurl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{\"status\":\"started\",\"message\":\"Build pipeline initiated\"}'' \\\n  \"http://build-management-service.build-pipeline:80/api/v1/builds/buildkit-test-$(date +%s)/status\" \\\n  2\u003e\u00261 | tee -a /logs/status-update-started.log\n\necho \"=== Status Update Completed ===\" | tee -a /logs/status-update-started.log\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-buildkit-external-rkvhb-3005675458
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: curlimages/curl:latest
          imagePullPolicy: Always
          name: main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /logs
              name: shared-workspace
              subPath: logs
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-mvftw
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
        - command:
            - argoexec
            - init
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: test-buildkit-external-rkvhb
            - name: ARGO_WORKFLOW_UID
              value: c3569cd4-fad6-4d6f-a0fe-1a5d15019d6f
            - name: ARGO_CONTAINER_NAME
              value: init
            - name: ARGO_TEMPLATE
              value: '{"name":"status-update-task","inputs":{"parameters":[{"name":"status","value":"started"},{"name":"message","value":"Build pipeline initiated"}]},"outputs":{},"metadata":{},"container":{"name":"","image":"curlimages/curl:latest","command":["sh","-c"],"args":["echo \"=== Status Update ===\" | tee /logs/status-update-started.log\necho \"Status: started\" | tee -a /logs/status-update-started.log\necho \"Message: Build pipeline initiated\" | tee -a /logs/status-update-started.log\necho \"Build ID: buildkit-test-$(date +%s)\" | tee -a /logs/status-update-started.log\necho \"Timestamp: $(date)\" | tee -a /logs/status-update-started.log\n\n# API call to update build status\ncurl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{\"status\":\"started\",\"message\":\"Build pipeline initiated\"}'' \\\n  \"http://build-management-service.build-pipeline:80/api/v1/builds/buildkit-test-$(date +%s)/status\" \\\n  2\u003e\u00261 | tee -a /logs/status-update-started.log\n\necho \"=== Status Update Completed ===\" | tee -a /logs/status-update-started.log\n"],"resources":{},"volumeMounts":[{"name":"shared-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-buildkit-external-rkvhb-3005675458
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-mvftw
              readOnly: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: var-run-argo
        - emptyDir: {}
          name: tmp-dir-argo
        - emptyDir: {}
          name: shared-workspace
        - name: kube-api-access-mvftw
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
