apiVersion: v1
kind: Pod
metadata:
    annotations:
        kubectl.kubernetes.io/default-container: main
        workflows.argoproj.io/node-id: test-minio-log-74b2c-1375133273
        workflows.argoproj.io/node-name: test-minio-log-74b2c.create-test-logs
        workflows.argoproj.io/report-outputs-completed: "true"
    labels:
        workflows.argoproj.io/completed: "false"
        workflows.argoproj.io/workflow: test-minio-log-74b2c
    name: test-minio-log-74b2c-create-logs-task-1375133273
    namespace: build-pipeline
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: Workflow
          name: test-minio-log-74b2c
          uid: b2b3591d-dc0d-4566-91f6-2d0687b75d3c
spec:
    containers:
        - command:
            - argoexec
            - wait
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: test-minio-log-74b2c
            - name: ARGO_WORKFLOW_UID
              value: b2b3591d-dc0d-4566-91f6-2d0687b75d3c
            - name: ARGO_CONTAINER_NAME
              value: wait
            - name: ARGO_TEMPLATE
              value: '{"name":"create-logs-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine:latest","command":["sh","-c"],"args":["echo \"=== Test Log Creation ===\" | tee /logs/test.log\necho \"Build ID: test-build-001\" | tee -a /logs/test.log\necho \"Timestamp: $(date)\" | tee -a /logs/test.log\necho \"This is a test log for MinIO upload\" | tee -a /logs/test.log\n\necho \"Creating multiple log files...\"\necho \"Git clone simulation\" \u003e /logs/git-clone.log\necho \"Container build simulation\" \u003e /logs/container-build.log\necho \"Status update simulation\" \u003e /logs/status-update.log\n\nls -la /logs/\necho \"=== Log Creation Completed ===\"\n"],"resources":{},"volumeMounts":[{"name":"test-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-minio-log-74b2c-1375133273
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: wait
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mainctrfs/logs
              name: test-workspace
              subPath: logs
            - mountPath: /tmp
              name: tmp-dir-argo
              subPath: "0"
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-qcvc6
              readOnly: true
        - args:
            - |
              echo "=== Test Log Creation ===" | tee /logs/test.log
              echo "Build ID: test-build-001" | tee -a /logs/test.log
              echo "Timestamp: $(date)" | tee -a /logs/test.log
              echo "This is a test log for MinIO upload" | tee -a /logs/test.log

              echo "Creating multiple log files..."
              echo "Git clone simulation" > /logs/git-clone.log
              echo "Container build simulation" > /logs/container-build.log
              echo "Status update simulation" > /logs/status-update.log

              ls -la /logs/
              echo "=== Log Creation Completed ==="
          command:
            - /var/run/argo/argoexec
            - emissary
            - --loglevel
            - info
            - --log-format
            - text
            - --
            - sh
            - -c
          env:
            - name: ARGO_CONTAINER_NAME
              value: main
            - name: ARGO_TEMPLATE
              value: '{"name":"create-logs-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine:latest","command":["sh","-c"],"args":["echo \"=== Test Log Creation ===\" | tee /logs/test.log\necho \"Build ID: test-build-001\" | tee -a /logs/test.log\necho \"Timestamp: $(date)\" | tee -a /logs/test.log\necho \"This is a test log for MinIO upload\" | tee -a /logs/test.log\n\necho \"Creating multiple log files...\"\necho \"Git clone simulation\" \u003e /logs/git-clone.log\necho \"Container build simulation\" \u003e /logs/container-build.log\necho \"Status update simulation\" \u003e /logs/status-update.log\n\nls -la /logs/\necho \"=== Log Creation Completed ===\"\n"],"resources":{},"volumeMounts":[{"name":"test-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-minio-log-74b2c-1375133273
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: alpine:latest
          imagePullPolicy: Always
          name: main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /logs
              name: test-workspace
              subPath: logs
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-qcvc6
              readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
        - command:
            - argoexec
            - init
            - --loglevel
            - info
            - --log-format
            - text
          env:
            - name: ARGO_POD_NAME
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            - name: ARGO_POD_UID
              valueFrom:
                fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.uid
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ARGO_WORKFLOW_NAME
              value: test-minio-log-74b2c
            - name: ARGO_WORKFLOW_UID
              value: b2b3591d-dc0d-4566-91f6-2d0687b75d3c
            - name: ARGO_CONTAINER_NAME
              value: init
            - name: ARGO_TEMPLATE
              value: '{"name":"create-logs-task","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"alpine:latest","command":["sh","-c"],"args":["echo \"=== Test Log Creation ===\" | tee /logs/test.log\necho \"Build ID: test-build-001\" | tee -a /logs/test.log\necho \"Timestamp: $(date)\" | tee -a /logs/test.log\necho \"This is a test log for MinIO upload\" | tee -a /logs/test.log\n\necho \"Creating multiple log files...\"\necho \"Git clone simulation\" \u003e /logs/git-clone.log\necho \"Container build simulation\" \u003e /logs/container-build.log\necho \"Status update simulation\" \u003e /logs/status-update.log\n\nls -la /logs/\necho \"=== Log Creation Completed ===\"\n"],"resources":{},"volumeMounts":[{"name":"test-workspace","mountPath":"/logs","subPath":"logs"}]}}'
            - name: ARGO_NODE_ID
              value: test-minio-log-74b2c-1375133273
            - name: ARGO_INCLUDE_SCRIPT_OUTPUT
              value: "false"
            - name: ARGO_DEADLINE
              value: "0001-01-01T00:00:00Z"
            - name: ARGO_PROGRESS_FILE
              value: /var/run/argo/progress
            - name: ARGO_PROGRESS_PATCH_TICK_DURATION
              value: 1m0s
            - name: ARGO_PROGRESS_FILE_TICK_DURATION
              value: 3s
          image: quay.io/argoproj/argoexec:v3.5.5
          imagePullPolicy: IfNotPresent
          name: init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/argo
              name: var-run-argo
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-qcvc6
              readOnly: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: workflow-service-account
    serviceAccountName: workflow-service-account
    terminationGracePeriodSeconds: 30
    tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
    volumes:
        - emptyDir: {}
          name: var-run-argo
        - emptyDir: {}
          name: tmp-dir-argo
        - emptyDir: {}
          name: test-workspace
        - name: kube-api-access-qcvc6
          projected:
            defaultMode: 420
            sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                        - key: ca.crt
                          path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
