apiVersion: batch/v1
kind: Job
metadata:
    annotations:
        batch.kubernetes.io/cronjob-scheduled-timestamp: "2025-07-12T13:12:00Z"
    labels:
        app: cluster-backup
        batch.kubernetes.io/controller-uid: 495e7f63-3ad7-4ea9-82a4-9b3fe7835ce4
        batch.kubernetes.io/job-name: backup-cronjob-test-29205432
        component: test-job
        controller-uid: 495e7f63-3ad7-4ea9-82a4-9b3fe7835ce4
        job-name: backup-cronjob-test-29205432
    name: backup-cronjob-test-29205432
    namespace: test-backup
    ownerReferences:
        - apiVersion: batch/v1
          blockOwnerDeletion: true
          controller: true
          kind: CronJob
          name: backup-cronjob-test
          uid: dc656275-ad42-4536-8a64-cdbd29096a94
spec:
    activeDeadlineSeconds: 300
    backoffLimit: 3
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
        matchLabels:
            batch.kubernetes.io/controller-uid: 495e7f63-3ad7-4ea9-82a4-9b3fe7835ce4
    suspend: false
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: cluster-backup
                batch.kubernetes.io/controller-uid: 495e7f63-3ad7-4ea9-82a4-9b3fe7835ce4
                batch.kubernetes.io/job-name: backup-cronjob-test-29205432
                component: test-job
                controller-uid: 495e7f63-3ad7-4ea9-82a4-9b3fe7835ce4
                job-name: backup-cronjob-test-29205432
        spec:
            containers:
                - env:
                    - name: CLUSTER_DOMAIN
                      valueFrom:
                        configMapKeyRef:
                            key: cluster-domain
                            name: backup-config
                    - name: CLUSTER_NAME
                      valueFrom:
                        configMapKeyRef:
                            key: cluster-name
                            name: backup-config
                    - name: MINIO_ENDPOINT
                      valueFrom:
                        configMapKeyRef:
                            key: minio-endpoint
                            name: backup-config
                    - name: MINIO_BUCKET
                      valueFrom:
                        configMapKeyRef:
                            key: minio-bucket
                            name: backup-config
                    - name: MINIO_USE_SSL
                      valueFrom:
                        configMapKeyRef:
                            key: minio-use-ssl
                            name: backup-config
                    - name: EXCLUDE_NAMESPACES
                      valueFrom:
                        configMapKeyRef:
                            key: exclude-namespaces
                            name: backup-config
                    - name: BATCH_SIZE
                      valueFrom:
                        configMapKeyRef:
                            key: batch-size
                            name: backup-config
                    - name: RETRY_ATTEMPTS
                      valueFrom:
                        configMapKeyRef:
                            key: retry-attempts
                            name: backup-config
                    - name: RETRY_DELAY
                      valueFrom:
                        configMapKeyRef:
                            key: retry-delay
                            name: backup-config
                    - name: LOG_LEVEL
                      valueFrom:
                        configMapKeyRef:
                            key: log-level
                            name: backup-config
                    - name: MINIO_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                            key: minio-access-key
                            name: backup-secrets
                    - name: MINIO_SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                            key: minio-secret-key
                            name: backup-secrets
                  image: cluster-backup:test
                  imagePullPolicy: Never
                  name: backup
                  ports:
                    - containerPort: 8080
                      name: metrics
                      protocol: TCP
                  resources:
                    limits:
                        cpu: 500m
                        memory: 512Mi
                    requests:
                        cpu: 100m
                        memory: 256Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext:
                fsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
            serviceAccount: cluster-backup
            serviceAccountName: cluster-backup
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: tmp
