apiVersion: batch/v1
kind: Job
metadata:
    annotations: {}
    labels:
        app: git-sync
        batch.kubernetes.io/controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
        batch.kubernetes.io/job-name: git-sync-minimal-test
        component: minimal-test
        controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
        job-name: git-sync-minimal-test
    name: git-sync-minimal-test
    namespace: test-backup
spec:
    activeDeadlineSeconds: 300
    backoffLimit: 1
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
        matchLabels:
            batch.kubernetes.io/controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
    suspend: false
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: git-sync
                batch.kubernetes.io/controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
                batch.kubernetes.io/job-name: git-sync-minimal-test
                component: minimal-test
                controller-uid: 646529e9-1fc7-4cac-a15a-5aa281fd1273
                job-name: git-sync-minimal-test
        spec:
            containers:
                - args:
                    - -c
                    - echo 'Testing git-sync environment' && echo 'WORK_DIR='$WORK_DIR && echo 'MINIO_ENDPOINT='$MINIO_ENDPOINT && ls -la /workspace && mkdir -p /workspace/test-dir && ls -la /workspace && echo 'Test completed successfully'
                  command:
                    - /bin/sh
                  env:
                    - name: WORK_DIR
                      valueFrom:
                        secretKeyRef:
                            key: work-dir
                            name: git-sync-secrets
                    - name: MINIO_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                            key: minio-endpoint
                            name: git-sync-secrets
                  image: alpine:latest
                  imagePullPolicy: Always
                  name: git-sync-test
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /workspace
                      name: workspace
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext:
                fsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
            serviceAccount: cluster-backup
            serviceAccountName: cluster-backup
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: workspace
