apiVersion: batch/v1
kind: Job
metadata:
    annotations: {}
    labels:
        app: cluster-backup
        component: secret-test
    name: secret-backup-test
    namespace: test-backup
spec:
    activeDeadlineSeconds: 300
    backoffLimit: 3
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
        matchLabels:
            batch.kubernetes.io/controller-uid: 582d99e4-b9dc-4017-82b4-4cf0bc771c0d
    suspend: false
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: cluster-backup
                batch.kubernetes.io/controller-uid: 582d99e4-b9dc-4017-82b4-4cf0bc771c0d
                batch.kubernetes.io/job-name: secret-backup-test
                component: secret-test
                controller-uid: 582d99e4-b9dc-4017-82b4-4cf0bc771c0d
                job-name: secret-backup-test
        spec:
            containers:
                - env:
                    - name: CLUSTER_DOMAIN
                      valueFrom:
                        secretKeyRef:
                            key: cluster-domain
                            name: backup-secrets
                    - name: CLUSTER_NAME
                      valueFrom:
                        secretKeyRef:
                            key: cluster-name
                            name: backup-secrets
                    - name: MINIO_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                            key: minio-endpoint
                            name: backup-secrets
                    - name: MINIO_BUCKET
                      valueFrom:
                        secretKeyRef:
                            key: minio-bucket
                            name: backup-secrets
                    - name: MINIO_USE_SSL
                      valueFrom:
                        secretKeyRef:
                            key: minio-use-ssl
                            name: backup-secrets
                    - name: EXCLUDE_NAMESPACES
                      valueFrom:
                        secretKeyRef:
                            key: exclude-namespaces
                            name: backup-secrets
                    - name: BATCH_SIZE
                      valueFrom:
                        secretKeyRef:
                            key: batch-size
                            name: backup-secrets
                    - name: RETRY_ATTEMPTS
                      valueFrom:
                        secretKeyRef:
                            key: retry-attempts
                            name: backup-secrets
                    - name: RETRY_DELAY
                      valueFrom:
                        secretKeyRef:
                            key: retry-delay
                            name: backup-secrets
                    - name: LOG_LEVEL
                      valueFrom:
                        secretKeyRef:
                            key: log-level
                            name: backup-secrets
                    - name: MINIO_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                            key: minio-access-key
                            name: backup-secrets
                    - name: MINIO_SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                            key: minio-secret-key
                            name: backup-secrets
                  image: cluster-backup:secret-test
                  imagePullPolicy: Never
                  name: backup
                  resources:
                    limits:
                        cpu: 500m
                        memory: 512Mi
                    requests:
                        cpu: 100m
                        memory: 256Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext:
                fsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
            serviceAccount: cluster-backup
            serviceAccountName: cluster-backup
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: tmp
