apiVersion: apps/v1
kind: Deployment
metadata:
    annotations: {}
    labels:
        app: buildkitd
    name: buildkitd
    namespace: buildkit
spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: buildkitd
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                prometheus.io/port: "1234"
                prometheus.io/scrape: "true"
            creationTimestamp: null
            labels:
                app: buildkitd
        spec:
            containers:
                - args:
                    - --addr=tcp://0.0.0.0:1234
                    - --debug
                  command:
                    - buildkitd
                  env:
                    - name: BUILDKIT_STEP_LOG_MAX_SIZE
                      value: "50000000"
                    - name: BUILDKIT_STEP_LOG_MAX_SPEED
                      value: "10000000"
                  image: moby/buildkit:latest
                  imagePullPolicy: Always
                  livenessProbe:
                    exec:
                        command:
                            - buildctl
                            - debug
                            - workers
                    failureThreshold: 3
                    initialDelaySeconds: 30
                    periodSeconds: 30
                    successThreshold: 1
                    timeoutSeconds: 10
                  name: buildkitd
                  ports:
                    - containerPort: 1234
                      name: tcp
                      protocol: TCP
                  readinessProbe:
                    exec:
                        command:
                            - buildctl
                            - debug
                            - workers
                    failureThreshold: 3
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    successThreshold: 1
                    timeoutSeconds: 5
                  resources:
                    limits:
                        cpu: "4"
                        memory: 8Gi
                    requests:
                        cpu: 500m
                        memory: 1Gi
                  securityContext:
                    privileged: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /var/lib/buildkit
                      name: buildkit-cache
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir:
                    sizeLimit: 20Gi
                  name: buildkit-cache
