---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  namespace: backup-system
  labels:
    app: cluster-backup
    component: secrets
type: Opaque
data:
  # MinIO Endpoint Configuration
  # echo -n "host.minikube.internal:9000" | base64
  minio-endpoint: "aG9zdC5taW5pa3ViZS5pbnRlcm5hbDo5MDAw"
  
  # MinIO Bucket Name
  # echo -n "cluster-backups" | base64
  minio-bucket: "Y2x1c3Rlci1iYWNrdXBz"
  
  # MinIO SSL Configuration
  # echo -n "false" | base64
  minio-use-ssl: "ZmFsc2U="
  
  # MinIO Access Credentials
  # echo -n "admin" | base64
  minio-access-key: "YWRtaW4="
  
  # echo -n "admin123456" | base64
  minio-secret-key: "YWRtaW4xMjM0NTY="
  
  # Cluster Configuration
  # echo -n "minikube.local" | base64
  cluster-domain: "bWluaWt1YmUubG9jYWw="
  
  # echo -n "test-cluster" | base64
  cluster-name: "dGVzdC1jbHVzdGVy"
  
  # Additional Configuration
  # echo -n "kube-system,kube-public" | base64
  exclude-namespaces: "a3ViZS1zeXN0ZW0sa3ViZS1wdWJsaWM="
  
  # echo -n "10" | base64
  batch-size: "MTA="
  
  # echo -n "3" | base64
  retry-attempts: "Mw=="
  
  # echo -n "5s" | base64
  retry-delay: "NXM="
  
  # echo -n "debug" | base64
  log-level: "ZGVidWc="