---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-backup
  namespace: backup-system
  labels:
    app: cluster-backup
    component: backup-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-backup-reader
  labels:
    app: cluster-backup
    component: backup-service
rules:
# Core resources
- apiGroups: [""]
  resources: 
    - pods
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    - serviceaccounts
    - endpoints
    - namespaces
  verbs: ["get", "list"]

# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
  verbs: ["get", "list"]

# Apps resources
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - daemonsets
    - statefulsets
  verbs: ["get", "list"]

# Extensions/Networking
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - networkpolicies
  verbs: ["get", "list"]

# Batch resources
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list"]

# Policy resources
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs: ["get", "list"]

# Autoscaling
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list"]

# Storage
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
    - csinodes
    - csidrivers
    - csistoragecapacities
  verbs: ["get", "list"]

# Admission Controllers
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    - validatingadmissionpolicies
    - validatingadmissionpolicybindings
  verbs: ["get", "list"]

# API Extensions
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list"]

# Certificates
- apiGroups: ["certificates.k8s.io"]
  resources:
    - certificatesigningrequests
  verbs: ["get", "list"]

# Coordination
- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs: ["get", "list"]

# Node
- apiGroups: ["node.k8s.io"]
  resources:
    - runtimeclasses
  verbs: ["get", "list"]

# Discovery
- apiGroups: ["discovery.k8s.io"]
  resources:
    - endpointslices
  verbs: ["get", "list"]

# Flow Control
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources:
    - flowschemas
    - prioritylevelconfigurations
  verbs: ["get", "list"]

# Scheduling
- apiGroups: ["scheduling.k8s.io"]
  resources:
    - priorityclasses
  verbs: ["get", "list"]

# OpenShift specific resources (if available)
- apiGroups: ["route.openshift.io"]
  resources:
    - routes
  verbs: ["get", "list"]

- apiGroups: ["build.openshift.io"]
  resources:
    - builds
    - buildconfigs
  verbs: ["get", "list"]

- apiGroups: ["image.openshift.io"]
  resources:
    - images
    - imagestreams
    - imagestreamtags
  verbs: ["get", "list"]

- apiGroups: ["apps.openshift.io"]
  resources:
    - deploymentconfigs
  verbs: ["get", "list"]

# Custom Resource Definitions (CRDs) - Allow discovery
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
  resourceNames: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-backup-binding
  labels:
    app: cluster-backup
    component: backup-service
subjects:
- kind: ServiceAccount
  name: cluster-backup
  namespace: backup-system
roleRef:
  kind: ClusterRole
  name: cluster-backup-reader
  apiGroup: rbac.authorization.k8s.io