apiVersion: v1
data:
    auth: YXV0aG9yaXphdGlvbiB7CiAgdG9rZW46ICJPekZWUjRKTVFFdDN5a3pwSFg3YXFkbDBkUWY4UDRuRDVWZWxZTEZmSVpVSEZndjZZNEU1aVJhOUlKRkVoZWtEIgp9
kind: Secret
metadata:
    annotations:
        resource-spec-hash: "2409867630"
        strategy: token
    labels:
        controller: eventbus-controller
        eventbus-name: default
        owner-name: default
        server-auth-secret: "yes"
    name: eventbus-default-server
    namespace: argo-events
    ownerReferences:
        - apiVersion: argoproj.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: EventBus
          name: default
          uid: edcc5fb2-7cd1-4c74-b347-1ed46f87cf32
type: Opaque
