apiVersion: apps/v1
kind: ReplicaSet
metadata:
    annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
    labels:
        app: argo-server
        pod-template-hash: 64f8c6b4d
    name: argo-server-64f8c6b4d
    namespace: argo
    ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: argo-server
          uid: dc9f710b-08b0-465a-8719-f6739704b8b6
spec:
    replicas: 1
    selector:
        matchLabels:
            app: argo-server
            pod-template-hash: 64f8c6b4d
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: argo-server
                pod-template-hash: 64f8c6b4d
        spec:
            containers:
                - args:
                    - server
                  image: quay.io/argoproj/argocli:v3.5.5
                  imagePullPolicy: IfNotPresent
                  name: argo-server
                  ports:
                    - containerPort: 2746
                      name: web
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /
                        port: 2746
                        scheme: HTTPS
                    initialDelaySeconds: 10
                    periodSeconds: 20
                    successThreshold: 1
                    timeoutSeconds: 1
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            dnsPolicy: ClusterFirst
            nodeSelector:
                kubernetes.io/os: linux
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
                runAsNonRoot: true
            serviceAccount: argo-server
            serviceAccountName: argo-server
            terminationGracePeriodSeconds: 30
            volumes:
                - emptyDir: {}
                  name: tmp
