---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync
  namespace: openshift-backup
  labels:
    app: git-sync
    component: git-sync-cronjob
spec:
  schedule: "0 4 * * *"  # Daily at 4 AM (2 hours after backup)
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 1800  # 30 minutes
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            app: git-sync
            component: git-sync-job
        spec:
          serviceAccountName: git-sync
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: git-sync
            image: registry.example.com/openshift/git-sync:latest
            imagePullPolicy: Always
            env:
            # MinIO Configuration
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-endpoint
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-bucket
            - name: MINIO_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-use-ssl
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: minio-secret-key
            # Git Configuration
            - name: GIT_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-repository
            - name: GIT_BRANCH
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-branch
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-username
            - name: GIT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-email
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: git-token
                  optional: true
            # Additional Configuration
            - name: WORK_DIR
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: work-dir
            - name: RETRY_ATTEMPTS
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: retry-attempts
            - name: RETRY_DELAY
              valueFrom:
                secretKeyRef:
                  name: git-sync-secrets
                  key: retry-delay
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: workspace
              mountPath: /workspace
            - name: ssh-key
              mountPath: /home/git-sync-user/.ssh
              readOnly: true
            ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /metrics
                port: metrics
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          volumes:
          - name: tmp
            emptyDir: {}
          - name: workspace
            emptyDir:
              sizeLimit: 10Gi
          - name: ssh-key
            secret:
              secretName: git-sync-secrets
              items:
              - key: ssh-private-key
                path: id_rsa
                mode: 0600
              defaultMode: 0600
              optional: true
          tolerations:
          - operator: Exists
            effect: NoSchedule
          - operator: Exists
            effect: NoExecute
          nodeSelector:
            kubernetes.io/os: linux
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-sync
  namespace: openshift-backup
  labels:
    app: git-sync
    component: service-account